import { Platform, StyleSheet } from 'react-native';
import CommonStyles from '../../CommonStyles';
import { whiteThemeColors,isTablet } from '../../../Utilities';

export const styles = StyleSheet.create({
  mainAnnouncementView: { flexDirection: 'row', marginTop: 20 },
  announcementText: { fontFamily: CommonStyles.fonts.semiBold, height: 30 },
  announcementArrow: {
    width: 30,
    height: 28,
    backgroundColor: whiteThemeColors.white,
    borderRadius: 5,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    right: 0,
    top: -5,
  },
  announcementRender: {
    width: isTablet ? '95%' : '90%',
    height: 80,
    backgroundColor: whiteThemeColors.white + 90,
    borderRadius: 10,
    alignItems: 'center',
    paddingHorizontal: 20,
    flexDirection: 'row',
    marginRight: 38,
  },
  announcementImage: {
    width: 50,
    height: 50,
    borderRadius: 10,
    backgroundColor: whiteThemeColors.primary + 60,
    justifyContent: 'center',
    alignItems: 'center',
  },
  announcementimage: {
    width: 30,
    height: 30,
    tintColor: whiteThemeColors.white,
  },
  announcementTitle: {
    fontFamily: CommonStyles.fonts.medium,
    fontSize: 13,
    width: '85%',
  },
  announcementDiscription: {
    marginTop: 4,
    paddingRight: 10,
    fontFamily: CommonStyles.fonts.light,
    fontSize: 10,
    color: whiteThemeColors.greyDark,
    textAlign: 'justify',
  },
  assignedCalendarHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: isTablet?'98%':'100%',
    marginBottom: 20,
    alignItems: 'center',
    alignSelf: 'center',
    marginLeft:isTablet?0: -15,
    
  },
  assignedCalendarleft: {
    width: 30,
    height: 30,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: whiteThemeColors.primary,
    borderRadius: 10,
  },
  assignedMonthDay: {
    width: 160,
    height: 30,
    backgroundColor: whiteThemeColors.primary,
    // marginLeft: -35,
    alignSelf: 'center',
    borderRadius: 10,
    justifyContent: 'center',
  },
  assignedMonthText: {
    fontFamily: CommonStyles.fonts.regular,
    color: 'white',
    textAlign: 'center',
  },
  assignedCalendarRight: {
    width: 30,
    height: 30,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: whiteThemeColors.primary,
    borderRadius: 10,
  },
  assignedMain: {
    width: '100%',
    borderRadius: 15,
  },
  assignedDashboard: {
    color: 'black',
    textAlign: 'left',
    fontSize: 14,
    width: '100%',
    marginTop: 40,
    fontFamily: CommonStyles.fonts.semiBold,
  },
  assignedCalendar: {
    paddingRight: 5,
    width: Platform.select({
      android: isTablet ? "100%" : '105%',
      ios: isTablet ? "105%" : '110%'
    }),
    marginLeft: Platform.OS == 'android' ? -8 : -20,
    marginTop: 10,
    backgroundColor: whiteThemeColors.background,
    borderRadius: 16,
    marginBottom: '20%',
    height: 300,
    paddingHorizontal: 10,
  },
  calendarTheme: {
    textSectionTitleColor: whiteThemeColors.primary,
    selectedDayBackgroundColor: whiteThemeColors.white,
    textDayHeaderFontFamily: CommonStyles.fonts.regular,
    selectedDayTextColor: whiteThemeColors.white,
    dayTextColor: whiteThemeColors.greyDark,
    textDayStyle: {
      fontFamily: CommonStyles.fonts.bold,
      color: whiteThemeColors.primary,
      textSize: 16,
      fontWeight: '500',
    },
    textDisabledColor: whiteThemeColors.greenLite,
    selectedDotColor: whiteThemeColors.primary,
    dotColor: whiteThemeColors.primary,
    arrowColor: whiteThemeColors.greyDark,
    monthTextColor: whiteThemeColors.greyDark,
    indicatorColor: whiteThemeColors.primary,
    textMonthFontFamily: CommonStyles.fonts.semiBold,
    textDayFontSize: 13,
    textDayFontFamily: CommonStyles.fonts.semiBold,
    textMonthFontSize: 13,
    textDayHeaderFontSize: 12,
    textDayHeaderFontWeight: 'bold',
    backgroundColor: 'transparent', // Set your desired background color here
    calendarBackground: 'transparent',
    'stylesheet.day.basic': {
      base: {
        width: 40,
        height: 40,
        justifyContent: 'center',
        alignItems: 'center',
        margin: -4,
        borderRadius: 15,
        backgroundColor: whiteThemeColors.white,
        shadowColor: '#000',
        elevation: 4,
        shadowOpacity: 0.09,
        shadowRadius: 3 * 1,
        shadowOffset: {
          height: 3 * 1,
          width: 3 * 1,
        },
      },
    },

    'stylesheet.calendar.header': {
      week: {
        marginTop: 0,
        flexDirection: 'row',
        justifyContent: 'space-around',
      },
      monthText: {
        fontSize: 12,
        fontFamily: CommonStyles.fonts.medium,
      },
    },
  },
});
