import { Platform, StyleSheet } from 'react-native';
import { hp } from '../../../../../Helpers/Responsiveness';
import { whiteThemeColors } from '../../../../../Utilities';

export const style = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: whiteThemeColors.background,
  },
  actionBtnContainer: {
    width: '100%',
    height: 50,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 5,
  },
  actionBtn: {
    backgroundColor: whiteThemeColors.primary + 30,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 5,
    flex: 1,
    height: 45,
  },
  actionBtnTxt: {
    color: whiteThemeColors.textColor.darkGrayText,
    fontSize: 12,
  },
  cardContainer: {
    flexDirection: 'column',
    marginTop: 25,
    height: Platform.OS === 'ios' ? 570 : 470,
  },
  bottomViewButton: {
    backgroundColor: whiteThemeColors.primary,
    alignItems: 'center',
    height: hp(4),
  },
  card: {
    backgroundColor: whiteThemeColors.white,
    width: '90%',
    borderRadius: 25,
    alignItems: 'center',
    justifyContent: 'space-around',
    flexDirection: 'column',
    paddingVertical: 20,
    height: Platform.OS === 'ios' ? 300 : 200,
    alignSelf: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 1,
  },
  info: {
    width: 70,
    height: 70,
    borderRadius: 35,
    backgroundColor: whiteThemeColors.primary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  button: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    alignItems: 'center',
    width: '90%',
  },
  chevronLftContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    position: 'absolute',
    bottom: 7,
    paddingHorizontal: 20,
  },
  chevronLft: {
    justifyContent: 'center',
    backgroundColor: whiteThemeColors.primary,
    shadowColor: whiteThemeColors.black,
    flexDirection: 'row',
    alignItems: 'center',
    height: 45,
    marginRight: 5,
    borderRadius: 10,
  },
  chevronThinLft: {
    marginLeft: 0,
    marginRight: 10,
    padding: 0,
  },
  previousTxt: {
    color: whiteThemeColors.white,
    margin: 0,
    paddingRight: 0,
  },
  btn: {
    justifyContent: 'center',
    backgroundColor: whiteThemeColors.greyLite,
    shadowColor: whiteThemeColors.black,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    flexDirection: 'row',
    alignItems: 'center',
    height: 45,
  },
  chevronRight: {
    justifyContent: 'center',
    backgroundColor: whiteThemeColors.primary,
    borderRadius: 10,

    flexDirection: 'row',
    alignItems: 'center',
    height: 45,
    marginRight: 5,
  },
  chevronThinRight: {
    marginLeft: 5,
    marginRight: 0,
    padding: 0,
  },
  nextText: {
    color: whiteThemeColors.white,
    margin: 0,
    paddingRight: 0,
  },
  btnText: {
    fontSize: 14,
    color: whiteThemeColors.white,
    margin: 0,
    paddingRight: 0,
  },
  mediaPlayer: {
    backgroundColor: whiteThemeColors.black,
    justifyContent: 'center',
    position: 'absolute',
    bottom: 0,
    right: 0,
    left: 0,
    top: 0,
  },
});
