import { Dimensions, StatusBar, StyleSheet } from 'react-native';
import CommonStyles from '../CommonStyles';
import { whiteThemeColors } from '../../Utilities';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    marginTop: StatusBar.currentHeight || 0,
  },
  itemContainer: {
    flexDirection: 'row',
    padding: 5,
    marginHorizontal: 10,
    borderRadius: 15,
    borderBottomColor: whiteThemeColors.primary,
    backgroundColor: whiteThemeColors.white + 90,
    marginTop: 2,
  },
  itemTitle: {
    color: whiteThemeColors.black,
    fontFamily: CommonStyles.fonts.medium,
  },
  getBtn: {
    position: 'absolute',
    right: 15,
    alignSelf: 'center',
    backgroundColor: whiteThemeColors.primary + 30,
    width: 25,
    height: 25,
    borderRadius: 7,
    justifyContent: 'center',
    alignItems: 'center',
  },
  btnText: {
    fontWeight: '600',
    fontSize: 16,
    textAlign: 'center',
    color: whiteThemeColors.white,
    marginRight: 2,
  },
  itemHomeworkText: {
    color: whiteThemeColors.greyDark,
    fontFamily: CommonStyles.fonts.regular,
    marginRight: 2,
    fontSize: 13,
    marginTop: 10,
  },
  noDataFoundContainer: {
    height: Dimensions.get('screen').height - 200,
    alignItems: 'center',
    justifyContent: 'center',
  },
  noDataFoundTxt: {
    alignSelf: 'center',
    marginTop: 200,
    fontSize: 15,
    color: whiteThemeColors.primaryTextColor,
    fontFamily: CommonStyles.fonts.medium,
  },
  img: {
    height: 80,
    width: 80,
    resizeMode: 'cover',
    borderRadius: 7,
    margin: 5,
  },
  nameContainer: {
    width: '60%',
    marginLeft: 10,
    marginVertical: 10,
  },
  titleCounterContainer: {
    alignItems: 'center',
    flexDirection: 'row',
  },
  item: {
    // height: 60,
    flexDirection: 'row',
    alignSelf: 'flex-start',
    marginLeft: 3,
    alignItems: 'center',
  },
  title: {
    color: whiteThemeColors.black,
    fontSize: 14,
    fontFamily: CommonStyles.fonts.medium,
    marginLeft: 7,
    width: '56%',
    textAlign: 'left',
  },
  labelText: {
    fontSize: 10,
    opacity: 0.7,
    color: whiteThemeColors.greyDark,
    fontFamily: CommonStyles.fonts.regular,
  },
  homeworkText: {
    fontSize: 10,
    alignSelf: 'center',
    color: whiteThemeColors.white,
    fontFamily: CommonStyles.fonts.medium,
  },
  loaderContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loaderTxt: {
    fontSize: 13,

    color: whiteThemeColors.greyDark,
    marginTop: 3,
  },
  cardSubContainer: {
    borderRadius: 15,

    alignItems: 'center',
    backgroundColor: whiteThemeColors.white + 90,
    marginHorizontal: 8,
    height: 140,
    width: '95%',
    flexDirection: 'row',
  },
  homeWorkIconContainer: {
    flex: 0.1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  homeworkTitleContainer: {
    flex: 0.5,
    marginLeft: 10,
  },
  statusContainer: {
    flexDirection: 'row',
    height: 20,

    borderRadius: 7,

    paddingHorizontal: 7,
    position: 'absolute',
    right: -15,
    // top: 25,
  },
  dateStatusContainer: {
    width: '90%',
    justifyContent: 'space-around',

    marginLeft: 10,
    marginTop: 5,
  },
  dateStatusSubContainer: {
    width: '50%',
    flexDirection: 'row',
    // paddingHorizontal: 20,
  },
  priorityTxt: {
    alignSelf: 'center',
    marginLeft: 5,
    fontSize: 10,
    textTransform: 'capitalize',
    fontFamily: CommonStyles.fonts.medium,
  },
  dateContainer: {
    // width: '40%',
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 5,
  },
  dateTxt: {
    alignSelf: 'center',
    marginLeft: 10,
    fontSize: 13,
    fontFamily: CommonStyles.fonts.medium,
  },
  btn: {
    position: 'absolute',
    right: -15,
    bottom: 1,
    backgroundColor: whiteThemeColors.primary + 30,
    width: 25,
    height: 25,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 7,
  },
  scoreStatusContainer: {
    paddingRight: 5,
    paddingLeft: 10,
    borderRadius: 50,
    flexDirection: 'row',
    alignItems: 'center',
    borderColor: whiteThemeColors.primaryDark + 'aa',
    marginTop: 20,
    // borderWidth: 1,
  },
  scoreStatusSubContainer: {
    height: 18,
    marginLeft: 15,
    marginVertical: 5,
    paddingHorizontal: 5,
    justifyContent: 'center',
    borderRadius: 6,
    elevation: 5,
  },
  scoreStatusTxt: {
    fontSize: 10,
    marginHorizontal: 10,
    color: whiteThemeColors.white,
    fontFamily: CommonStyles.fonts.medium,
  },
});
