import { StyleSheet } from 'react-native';
import CommonStyles from '../../../../CommonStyles';
import { whiteThemeColors } from 'utilities';

export const styles = StyleSheet.create({
  container: {
    backgroundColor: whiteThemeColors.white + 90,
    width: '97%',
    borderRadius: 20,
    marginTop: 10,
    flexDirection: 'row',
    alignSelf: 'center',
  },
  bottom: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginTop: 10,
    position: 'absolute',
    bottom: 7,
  },
  header: {
    position: 'absolute',
    top: 10,
    alignItems: 'center',
  },
  cardItem: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  cardItemKey_Text: {
    fontSize: 10,
    color: whiteThemeColors.black + 50,
    fontFamily: CommonStyles.fonts.medium,
    marginTop: 2,
  },
  markText: {
    color: whiteThemeColors.white,
    marginLeft: 10,
    fontSize: 10,
    fontFamily: CommonStyles.fonts.semiBold,
  },
  cardItemValue_Text: {
    fontSize: 10,
    fontFamily: CommonStyles.fonts.medium,
    marginLeft: 5,
    color: whiteThemeColors.black,
    marginTop: 2,
  },
  cardActiveKey_Text: {
    fontSize: 12,
    color: whiteThemeColors.greyDark,
    fontFamily: CommonStyles.fonts.semiBold,
  },
  cardActiveValue_Text: {
    fontSize: 10,
    color: whiteThemeColors.greyDark,
    fontFamily: CommonStyles.fonts.medium,

    marginLeft: 5,
    width: '100%',
    paddingHorizontal: 5,
    textAlign: 'center',
  },
  statusContainer: {
    alignItems: 'center',
    borderBottomLeftRadius: 10,
    width: '30%',
  },
  container2: {
    backgroundColor: whiteThemeColors.white,
    padding: 5,
    paddingHorizontal: 10,
    width: '70%',
    borderTopLeftRadius: 20,
    borderBottomLeftRadius: 20,
    // borderTopRightRadius: 150,
    justifyContent: 'center',
    paddingLeft: 15,
    paddingVertical: 15,
  },
  textContainer: {
    position: 'absolute',
    alignItems: 'center',
    width: '90%',
    right: 10,
    top: 10,
  },
  changeStatusCont: {
    backgroundColor: whiteThemeColors.primary,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    flexDirection: 'row',
    paddingHorizontal: 4,
    borderRadius: 5,
    padding: 3,
    bottom: 7,
  },
  changeStatusText: {
    color: whiteThemeColors.black,
    fontSize: 10,
  },
  statusText: {
    fontSize: 11,
    color: whiteThemeColors.primaryTextColor,
    fontFamily: CommonStyles.fonts.semiBold,
    paddingHorizontal: 8,
    textAlign: 'center',
    padding: 1,
  },
  countView: {
    backgroundColor: '#F29339',
    width: 18,
    height: 18,
    borderRadius: 9,
    margin: 4,
    justifyContent: 'center',
    alignItems: 'center',
  },
  countText: {
    fontSize: 10,

    color: whiteThemeColors.white,
  },
  markBtn: {
    backgroundColor: whiteThemeColors.primary,
    width: '85%',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    flexDirection: 'row',
    shadowColor: '#000',
    paddingVertical: 3,
    borderRadius: 8,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    bottom: 10,
  },
});
