import { Platform, StyleSheet } from 'react-native';
import CommonStyles from '../../../../CommonStyles';
import { whiteThemeColors } from '../../../../../Utilities';

export const styles = StyleSheet.create({
  container: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  form: {
    padding: 10,
    marginTop: 10,
  },
  input: {
    marginBottom: 10,
    height: 40,
    flexDirection: 'row',
  },
  dropdownStyle: {
    width: 200,
    height: 100,
    alignSelf: 'center',
    backgroundColor: whiteThemeColors.white,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 3,
    marginTop: Platform.OS === 'ios' ? 13 : -13,
    borderRadius: 10,
  },
  inputText: {
    paddingLeft: 15,
    fontSize: 12,
    color: whiteThemeColors.greyDark,
    fontFamily: CommonStyles.fonts.regular,
    // borderWidth: 0.5,
    height: 40,
    borderColor: whiteThemeColors.greyDark + 50,
    borderRadius: 10,
    backgroundColor: whiteThemeColors.white + 90,
  },
  textboxTitle: {
    paddingLeft: 5,
    paddingBottom: 2,
    fontSize: 12,
    fontFamily: CommonStyles.fonts.semiBold,
    color: whiteThemeColors.primaryTextColor,
    marginTop: 10,
  },
  dropDownRow: {
    flexDirection: 'row',
    marginTop: 0,
    marginBottom: 0,
    alignItems: 'center',
    height: 40,
    backgroundColor: whiteThemeColors.white,
  },
  button: {
    marginTop: 10,
    marginBottom: 50,
    height: 40,
    width: '100%',
    textAlign: 'center',
    justifyContent: 'center',
    alignItems: 'center',
  },
  manageButton: {
    width: '23%',
    height: 40,
    textAlign: 'center',
    justifyContent: 'center',
    backgroundColor: whiteThemeColors.primary,
    alignItems: 'center',
    marginLeft: 20,
  },
  buttonText: {
    color: whiteThemeColors.white,
    fontSize: 14,
    fontFamily: CommonStyles.fonts.semiBold,
    textAlign: 'center',
  },
  tagContainer: {
    marginLeft: 5,
    borderRadius: 3,
    justifyContent: 'center',
    flexDirection: 'row',
  },
  tagText: {
    color: 'white',
    fontSize: 12,
    paddingHorizontal: 5,
    paddingVertical: 3,
  },
  tagCross: {
    color: 'white',
    paddingRight: 4,
    fontSize: 12,
    alignSelf: 'center',
  },
  tagParentContainer: {
    height: 40,
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomColor: 'white',
  },
  tagsInput: {
    width: '80%',
    borderBottomRightRadius: 10,
    borderTopRightRadius: 10,
    borderLeftWidth: 0.5,
    borderColor: 'gray',

    backgroundColor: whiteThemeColors.white + 90,
  },
  itemImage: {
    width: 60,
    height: 60,
    borderRadius: 5,
    marginLeft: 8,
    marginTop: 20,
    marginBottom: 20,
  },
  imagePickerView: {
    backgroundColor: whiteThemeColors.primary,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 8,
    padding: 15,
  },
  imagePicker: {
    flexDirection: 'row',
    marginLeft: 5,
    marginTop: 15,
  },
  imageNameContainer: {
    justifyContent: 'center',
    width: '100%',
  },
  text: {
    padding: 10,
    fontSize: 12,
    fontFamily: CommonStyles.fonts.medium,
    color: whiteThemeColors.greyDark,
  },
  spinerInput: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  catContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    width: '98%',
    borderRadius: 10,
  },
});
