import { Platform, StyleSheet } from 'react-native';
import CommonStyles from '../../../../../CommonStyles';
import { whiteThemeColors } from 'utilities';

export const styles = StyleSheet.create({
  innerContainer: {
    alignItems: 'center',
    paddingVertical: 15,
    paddingHorizontal: 15,
    width: '93%',
    minHeight: 150,
    borderRadius: 20,
    overflow: Platform.OS == 'android' ? 'hidden' : 'visible',
    backgroundColor: whiteThemeColors.white + 90,
    marginTop: 10,
    alignSelf: 'center',
  },
  headerContainer: {
    width: '100%',
    padding: 5,
    alignSelf: 'flex-start',
  },
  modalHeaderContainer: {
    padding: 5,
    width: '110%',
    paddingHorizontal: '5%',
    backgroundColor: whiteThemeColors.background,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  modalHeaderContainer1: {
    padding: 5,
    width: '110%',
    paddingHorizontal: '5%',
    backgroundColor: whiteThemeColors.background,
    flexDirection: 'row',
    justifyContent: 'space-between',
    elevation: 5,
    shadowColor: whiteThemeColors.black,
    shadowRadius: 5,
    shadowOffset: {
      height: 2,
      width: 0,
    },
    shadowOpacity: 0.09,
  },
  labelText: {
    fontSize: 12,
    opacity: 0.7,
    color: whiteThemeColors.greyDark,
    fontFamily: CommonStyles.fonts.regular,
  },
  btnContainer: {
    width: '100%',
    flexDirection: 'row',
  },
  btnView: {
    flexDirection: 'row',
    paddingHorizontal: 15,
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  text: {
    color: whiteThemeColors.primary,
    marginBottom: 10,
    fontFamily: CommonStyles.fonts.medium,
  },
  btn: {
    height: 28,
    borderRadius: 7,
    marginTop: 10,
    marginRight: 10,
    shadowColor: whiteThemeColors.black,
    backgroundColor: whiteThemeColors.primary,
  },
  noInfoContainer: {
    alignItems: 'center',
    width: '100%',
    height: '80%',
    justifyContent: 'center',
    marginVertical: 10,
  },
  noInfo: {
    color: whiteThemeColors.lightBlack,
    fontFamily: CommonStyles.fonts.regular,
    marginTop: 20,
  },
  feedbackContainer: {
    width: '90%',
    paddingHorizontal: 10,
    marginBottom: 20,
    minHeight: '20%',
  },
  modalHeaderText: {
    fontSize: 20,
    color: whiteThemeColors.primaryTextColor,
    fontFamily: CommonStyles.fonts.semiBold,
    padding: 10,
  },
  messageContainer: {
    width: '100%',
    justifyContent: 'flex-end',
    alignItems: 'flex-end',
    paddingVertical: 10,
  },
  feedbackMsgContainer: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'flex-end',
  },
  textContainer: {
    padding: 10,
    borderRadius: 20,
    maxWidth: '80%',
    borderBottomRightRadius: 5,
    backgroundColor: whiteThemeColors.primary,
    opacity: 0.8,
    marginRight: 10,
    marginBottom: 10,
  },
  msgAvatar: {
    height: 40,
    width: 40,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 20,
    backgroundColor: whiteThemeColors.primary,
  },
  avatarName: {
    fontSize: 12,
    color: whiteThemeColors.greyDark,
    opacity: 0.8,
    marginRight: 50,
  },
  modalMainContainer: {
    flex: 1,
    backgroundColor: whiteThemeColors.greyDark + '80',
    justifyContent: 'flex-end',
  },
  modalContainer: {
    width: '100%',
    alignItems: 'center',
    marginTop: 200,
    minHeight: 150,
    backgroundColor: whiteThemeColors.background,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    elevation: 20,
    shadowRadius: 5,
    shadowColor: whiteThemeColors.black,
    shadowOpacity: 0.09,
    shadowOffset: {
      height: -2,
      width: 0,
    },
    maxHeight: '80%',
  },
  line: {
    marginVertical: 10,
    marginLeft: '1%',
    width: '98%',
    borderWidth: 0.5,
    opacity: 0.2,
    borderColor: whiteThemeColors.primary,
  },
  centerTxt: {
    fontSize: 13,
    color: whiteThemeColors.white,
    fontFamily: CommonStyles.fonts.semiBold,
  },
  contactStd: {
    fontSize: 13,
    color: whiteThemeColors.white,
    fontFamily: CommonStyles.fonts.semiBold,
  },
  txt: {
    fontSize: 12,
    color: whiteThemeColors.white,
    marginBottom: 5,
  },
  dateTxt: {
    fontSize: 10,
    color: whiteThemeColors.white,
    textAlign: 'right',
    marginBottom: -5,
  },
});
