import { Dimensions, Platform, StyleSheet } from 'react-native';
import { getHeight, scale, whiteThemeColors,isTablet } from '../../Utilities';
import CommonStyles from '../CommonStyles';
const deviceWidth = Dimensions.get('window').width;
const styles = StyleSheet.create({
  topView: {
    // zIndex: 10,
    // height: getHeight("14%"),
    height: 130,
    // marginTop: -1,
    width: '100%',
    borderRadius: 10,
    marginTop: 10,
  },
  counterTopView: {
    height: getHeight(200),
    width: deviceWidth,
  },
  scrollContainer: {
    backgroundColor: whiteThemeColors.background,
    paddingBottom: 90,
    paddingHorizontal: 20,
  },
  container2: {
    backgroundColor: whiteThemeColors.primary,
    marginTop: 15,
  },

  centerView: {
    justifyContent: 'center',
    // alignItems: 'center',
  },
  centerView1: {
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
  },
  GraphTitle: {
    textAlign: 'center',
    width: '100%',
    fontSize: 18,
    fontWeight: '600',
    height: 29,
    paddingLeft: 10,
    marginBottom: 10,
    paddingTop: 1,
  },
  ChartMarginTop: {
    marginTop: 12,
  },
  CounterHeaderText: {
    fontWeight: '600',
    marginTop: 5,
    textAlign: 'center',
    fontSize: 16,
  },
  TopCounterStyle: {
    flexDirection: 'column',
    width: '25%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  stat_box: {
    flexDirection: 'column',
    margin: 1,
    width: 80,
    height: 80,
    // borderWidth: 2,
    borderRadius: 40,
    alignItems: 'center',
    justifyContent: 'space-around',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.35,
    shadowRadius: 2.84,

    elevation: 5,
  },
  count_text_large: {
    fontSize: 16,
    fontWeight: 'bold',
    marginTop: -10,
  },
  welcomeView: {
    flex: 1,
    zIndex: 20,
    width: '100%',
    // height: 45,
  },
  welcomeViewText: {
    fontSize: 20,
    fontFamily: CommonStyles.fonts.semiBold,
  },
  welcomeViewTextBody: {
    flex: 2,
    flexDirection: 'row',
  },
  main_box: {
    position: 'absolute',
    zIndex: 10,
    top: 15,
    height: 150,
    width: '89%',
    alignSelf: 'center',
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    backgroundColor: whiteThemeColors.dashboardTopBoxBG,
    borderWidth: 1,
    borderColor: whiteThemeColors.white,
    borderRadius: 15,
  },
  container: {
    // margin: 6,
    marginTop: 20,
  },
  mTop8: {
    marginTop: 8,
  },
  studentParentCounterTopView: {},
  courseNameView: {
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 20,
  },
  courseName: {
    fontSize: 18,
    width: '90%',
  },
  courseFontcolor: {
    fontWeight: '600',
  },
  coinStack: {
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
  },
  courseViewCard: {
    flex: 1,
    flexDirection: 'row',
    marginTop: 2,
    justifyContent: 'space-around',
    alignItems: 'center',
  },
  ChildDropDownItem: {
    flex: 1,
    flexDirection: 'row',
  },
  pickerheaderTitleStyle: {
    marginLeft: 50,
    width: 160,
  },
  studentOverallPointTopView: {
    width: '100.5%',
    flex: 1,
    height: 200,
    flexDirection: 'column',
    margin: 3,
    marginLeft: 0,
    marginRight: 1.5,
    // padding: 3,
    paddingLeft: 0,
  },
  studentOverallPointTopViewHeader: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: whiteThemeColors.icons.studentOverallPointBg,
    height: 30,
  },
  studentCourseTicket: {
    flex: 1,

    padding: 3,
  },
  noActiveStudent: {
    marginLeft: 80,
    width: 250,
    height: 240,
  },
  noEnrollnment: {
    height: 150,
    justifyContent: 'center',
    alignItems: 'center',
  },
  calender: {
    marginLeft: 0,
    paddingLeft: 0,
    marginTop: 10,
    height: 400,
    marginBottom: 20,
  },
  modalStyle: {
    padding: '3%',
    flexDirection: 'column',
    alignSelf: 'center',
    alignContent: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    width: '92%',
    height: '75%',
    backgroundColor: whiteThemeColors.greyLite,
    opacity: 1,
    borderRadius: 15,
    shadowOffset: {
      height: 10,
      width: 2,
    },
    shadowRadius: 10,
  },
  modalButtonStyle: {
    alignContent: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    width: '90%',
    height: 45,
    alignSelf: 'center',
    borderRadius: 5,
    backgroundColor: CommonStyles.themeClr.backgroundColor,
    shadowOffset: {
      height: 3,
      width: 1,
    },
    shadowRadius: 10,
    opacity: 1,
  },
  modalButtonText: {
    justifyContent: 'center',

    fontWeight: 'bold',
    fontSize: 14,
  },
  modalContainer: {
    width: '100%',
  },
  modalCard: {
    flexDirection: 'column',
    flex: 1,
    padding: '5%',
    marginBottom: 5,
    width: '96%',
    borderRadius: 10,
    borderRightRadius: 20,
    opacity: 0.8,
    backgroundColor: whiteThemeColors.white,
    borderWidth: 0,
    borderColor: whiteThemeColors.blueLite,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
    elevation: 1,
    marginTop: 5,
    alignSelf: 'center',
  },
  View1: { flex: 1, flexDirection: 'row', height: 'auto', width: '100%' },
  View2: {
    flex: 1,
    flexDirection: 'row',
    height: 'auto',
    width: scale(0.42),
    alignSelf: 'center',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 2,
    backgroundColor: 'red',
  },
  View11: { width: '25%', justifyContent: 'center' },
  View12: { width: '75%', flexDirection: 'row' },
  View21: {
    // width: scale(0.18),
    justifyContent: 'center',
    alignContent: 'center',
    alignItems: 'center',
  },
  View22: {
    width: scale(0.18),
    justifyContent: 'center',
    alignItems: 'center',
  },
  // Class Name User Name Standard Size
  className: {
    fontSize: 13,
    fontWeight: 'bold',
  },
  classTime: {
    fontSize: 13,
  },
  time: {
    fontSize: 13,
    fontWeight: 'bold',
  },
  timeHeader: {
    fontSize: 13,
  },
  dateHeader: {
    color: whiteThemeColors.white,
    fontSize: 20,
    lineHeight: 90,
    height: 90,
    fontWeight: 'bold',
    alignContent: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 10,
  },

  dropDownContainer: {
    width: '60%',
    backgroundColor: whiteThemeColors.white,
    elevation: 5,
    marginTop: 5,
    marginLeft: 2,
    borderRadius: 5,
  },
  dropDownText: {
    padding: 2,
    marginVertical: 2,
    color: whiteThemeColors.black,
    fontSize: 15,
  },
  singleSector: {
    flex: 1,

    justifyContent: 'center',
    alignItems: 'center',
  },

  counterText: {
    fontSize: 14,
    fontWeight: 'bold',
    marginTop: 20,
    color: whiteThemeColors.white,
  },
  titleText: {
    fontWeight: '600',
    textAlign: 'center',
    fontSize: 12,

    color: whiteThemeColors.white,
    width: '80%',
    lineHeight: 14,
    // marginTop: 5,
  },
  key: {
    fontSize: 12,
    fontWeight: '600',

    color: whiteThemeColors.greyDark,
    marginTop: 10,
  },
  value: {
    fontSize: 12,

    marginTop: 10,
    color: whiteThemeColors.primary,
    marginLeft: 20,
  },
  header: {
    backgroundColor: whiteThemeColors.primary,
    paddingHorizontal: 10,
    height: 90,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    paddingTop: 20,
  },
  close: {
    marginRight: 10,
    position: 'absolute',
    left: 15,
    bottom: 16,
  },
  emptyList: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  emptyListText: {
    marginTop: 20,
    alignSelf: 'center',
    color: whiteThemeColors.greyDark,
  },
  onlineClassCard: {
    borderRadius: 10,
    marginHorizontal: 10,
    height: isTablet ? 140 : 90,
    backgroundColor: whiteThemeColors.white,
    flexDirection: 'row',
    alignItems: 'center',
  },
  imgContainer: {
    width: isTablet ? 155 : 100,
    justifyContent: 'center',
    alignItems: 'center',
    height: '100%',
    borderTopLeftRadius: 10,
    borderBottomLeftRadius: 10,
    padding: 6,
  },
  textContainer: {
    flex: 0.8,
    paddingHorizontal: 10,
    paddingRight: 20,
  },
  counterTextview: {
    flex: 1,
    borderBottomWidth: 0.3,
    borderBottomColor: 'gray',
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    marginLeft: 10,
  },
  containerbar: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  chart: {
    marginVertical: 8,
    borderRadius: 16,
  },
  cardContainer: {
    flex: 1,
    alignItems: 'center',
    marginHorizontal: 2,
    gap: 5,
  },
  linksCard: {
    width: 60, // Set a fixed width
    height: 60, // Set a fixed height
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  linkText: {
    fontSize: 10,
    fontFamily: CommonStyles.fonts.regular,
    width: 70,
    textAlign:"center"
  },
  joinContainer: {
    width: '100%',
    height: 60,
    marginTop: 20,
    backgroundColor: whiteThemeColors.white + 90,
    borderRadius: 10,
    marginBottom: 10,
    flexDirection: 'row',
    alignItems: 'center',
  },
  vectorIconCon: {
    width: 40,
    height: '100%',
    backgroundColor: whiteThemeColors.primary,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    alignSelf: 'center',
    right: 0,
    borderTopRightRadius: 10,
    borderBottomRightRadius: 10,
  },
  textCont: {
    flexDirection: 'row',
    justifyContent: 'space-between',

    paddingVertical: 20,
    // marginHorizontal: 40,
    backgroundColor: whiteThemeColors.white + 90,
    borderRadius: 10,
    // marginLeft: 10,
    marginTop: 10,
    alignItems: 'center',
    width: '48%',

    // width: '95%',
  },
  cardContainer2: {
    width: Platform.OS?"46%":'47%',
    height: 80,
    backgroundColor: whiteThemeColors.white + 90,
    justifyContent: 'center',
    borderRadius: 10,
    alignItems: 'center',
  },
  icon: {
    width: 60,
    height: 60,
    tintColor: whiteThemeColors.primary + 10,
    position: 'absolute',
    left: 20,
  },
  title: {
    fontFamily: CommonStyles.fonts.regular,
    marginTop: 5,
    fontSize: 12,
  },
  count: {
    fontFamily: CommonStyles.fonts.semiBold,
    fontSize: 18,
    marginTop: 5,
  },
  card: {
    width: 180,
    height: 150,
    marginRight: 10,
    backgroundColor: whiteThemeColors.primary + 30,
    borderRadius: 10,
    padding: 10,
  },
  pointsIcon: {
    width: '100%',
    height: 40,
    backgroundColor: whiteThemeColors.primary,
    borderRadius: 10,
    alignSelf: 'center',
    position: 'absolute',
    bottom: 10,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  pointsText: {
    fontFamily: CommonStyles.fonts.semiBold,
    color: 'white',
    marginLeft: 20,
  },
});

export default styles;
