import { Platform, StyleSheet } from 'react-native';
import CommonStyles from 'screens/CommonStyles';
import { whiteThemeColors } from 'utilities';
export const styles = StyleSheet.create({
  cardContainer: {
    width: '100%',
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
    borderRadius: 10,
    backgroundColor: whiteThemeColors.background,
    paddingVertical: 20,
    marginVertical: 8,
  },
  innerContainer: {
    alignItems: 'center',
    marginTop: 10,
    paddingVertical: 15,
    paddingHorizontal: 15,
    width: '90%',
    borderRadius: 20,
    overflow: Platform.OS == 'android' ? 'hidden' : 'visible',
    backgroundColor: whiteThemeColors.white + 90,
  },
  headerText: {
    fontSize: 21,
    color: whiteThemeColors.primaryTextColor,
    textTransform: 'capitalize',
    fontFamily: CommonStyles.fonts.semiBold,
  },
  showContacts: {
    backgroundColor: whiteThemeColors.primary,
    height: 20,
    justifyContent: 'center',
    width: 20,
    borderRadius: 7,
    alignSelf: 'flex-end',
  },
  showContactsContainer: {
    alignSelf: 'center',
    alignItems: 'center',
    marginTop: 15,
  },
  detailscon: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    borderBottomWidth: 1,
    borderBottomColor: whiteThemeColors.greyLite,
    paddingVertical: 15,
  },
  keyText: {
    fontSize: 12,
    fontFamily: CommonStyles.fonts.medium,
  },
  valueText: {
    fontSize: 12,
    color: whiteThemeColors.greyDark,
    fontFamily: CommonStyles.fonts.regular,
  },
  showContactstext: {
    color: whiteThemeColors.black,
    marginRight: 5,
    fontSize: 12,
    fontFamily: CommonStyles.fonts.regular,
  },
  imageContainer: {
    width: 90,
    height: 90,
    borderRadius: 45,
    backgroundColor: whiteThemeColors.white,
    justifyContent: 'center',
    alignItems: 'center',
  },
  staffId: {
    marginTop: -10,
    fontSize: 13,
    marginBottom: 10,
    fontWeight: '500',
    color: whiteThemeColors.greyDark,
  },
  status: {
    width: 14,
    height: 14,
    borderRadius: 8,
    position: 'absolute',
    bottom: 10,
    right: 3,
    zIndex: 10,
  },
  joiningDate: {
    fontSize: 10,
    paddingBottom: 10,
    alignSelf: 'flex-end',
    textAlign: 'right',
    color: whiteThemeColors.greyDark,
    fontFamily: CommonStyles.fonts.medium,
  },
  loaderContainer: {
    marginTop: 30,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  updateInfoBtn: {
    borderWidth: 1,
    borderColor: whiteThemeColors.primaryDark + 80,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    marginTop: 6,
    borderRadius: 10,
    paddingVertical: 7,
    justifyContent: 'center',
    backgroundColor: whiteThemeColors.primary + 20,
    width: 200,
    alignSelf: 'center',
  },
  updateInfoTxt: {
    color: whiteThemeColors.primaryDark,
    marginLeft: 10,
    fontSize: 12,
    fontFamily: CommonStyles.fonts.semiBold,
  },
  showBtn: {
    borderWidth: 1,
    borderColor: whiteThemeColors.primaryDark + 80,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    marginTop: 6,
    borderRadius: 10,
    paddingVertical: 7,
    justifyContent: 'center',
    backgroundColor: whiteThemeColors.primary + 20,
    width: 200,
    alignSelf: 'center',
  },
  showBtnTxt: {
    color: whiteThemeColors.primaryDark,
    marginLeft: 10,
    fontSize: 12,
    fontFamily: CommonStyles.fonts.semiBold,
  },
});
