import { Dimensions, Platform, StyleSheet } from 'react-native';
import { whiteThemeColors } from '../../../../../Utilities';
import { isTablet } from '../../../../../components';
import { hp } from '../../../../../Helpers/Responsiveness';
import CommonStyles from '../../../../CommonStyles';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    width: '100%',
    flexGrow: 1,
    backgroundColor: whiteThemeColors.background,
  },
  downloadContainer: {
    width: '100%',
    height: hp(15),
    alignSelf: 'center',
    marginTop: hp(5),
  },
  title: {
    marginTop: 70,
    marginLeft: 20,

    fontSize: 16,
    fontFamily: CommonStyles.fonts.semiBold,
    alignSelf: 'center',
    color: whiteThemeColors.greyDark,
  },
  name: {
    marginTop: 5,
    marginLeft: 20,
    alignSelf: 'center',
    color: whiteThemeColors.black,
    fontFamily: CommonStyles.fonts.regular,
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 7,
    marginTop: 20,
  },
  buttonViewFile: {
    borderRadius: 10,
    marginTop: 20,
    marginRight: 5,
    justifyContent: 'center',
    alignSelf: 'flex-end',
    shadowColor: whiteThemeColors.black,
    backgroundColor: whiteThemeColors.primary,
    alignItems: 'center',
    height: 40,
  },
  buttonDownload: {
    backgroundColor: whiteThemeColors.primary,
    width: '45%',
    borderRadius: 10,
    marginTop: 20,
    marginRight: 5,
    justifyContent: 'center',
    alignSelf: 'flex-end',
    elevation: 5,
    flexDirection: 'row',
    alignItems: 'center',
    height: 40,
  },
  markAsCompleteBtn: {
    borderRadius: 12,
    justifyContent: 'center',
    flexDirection: 'row',
    backgroundColor: whiteThemeColors.primary,
    height: 40,
    alignItems: 'center',
  },
  modalContainer: {
    flex: 1,
    height: '60%',
    width: '100%',
  },
  pdf: {
    flex: 1,
    zIndex: 1,
    width: Dimensions.get('window').width,
    height: Dimensions.get('window').height - 200,
  },
  webView: {
    width: '100%',
    height: '100%',
    marginTop: Platform.OS != 'ios' ? -33 : 30,
  },
  spinnerContainer: {
    flex: 1,
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
  },
  spinnerText: {
    fontSize: 20,
    color: whiteThemeColors.primary,
  },
  closeBtnContainer: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 15,
  },
  closeBtn: {
    height: 45,
    width: 45,
    borderRadius: 25,
    backgroundColor: whiteThemeColors.greyDark + '90',
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10,
  },
  footer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingBottom: Platform.OS === 'ios' ? (isTablet ? 5 : hp(2.5)) : 5,
    paddingHorizontal: 10,
    backgroundColor: whiteThemeColors.background,
  },
  leftChevron: {
    width: '45%',
    marginHorizontal: 1,
    justifyContent: 'center',
    backgroundColor: whiteThemeColors.primary + 30,
    borderRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
    height: 45,
  },
  previousStep: {
    margin: 0,
    paddingLeft: 0,
    color: whiteThemeColors.black,
    fontFamily: CommonStyles.fonts.medium,
  },
  chevron: {
    marginLeft: 0,
    marginRight: 0,
    padding: 0,
  },
  rightChevron: {
    width: '45%',
    marginHorizontal: 1,
    justifyContent: 'center',
    backgroundColor: whiteThemeColors.primary + 30,
    shadowColor: whiteThemeColors.black,
    flexDirection: 'row',
    alignItems: 'center',
    height: 45,
    borderRadius: 10,
  },
  nextStep: {
    margin: 0,
    paddingRight: 0,
    color: whiteThemeColors.black,
    fontFamily: CommonStyles.fonts.medium,
  },
  btnContainer: {
    width: '100%',
    height: 30,
    justifyContent: 'space-evenly',
    alignItems: 'center',
    alignSelf: 'center',
    flexDirection: 'row',
    marginBottom: 200,
    marginTop: '5%',
  },
});
