import { Platform, StyleSheet } from 'react-native';
import CommonStyles from '../../../../../../CommonStyles';
import { whiteThemeColors } from 'utilities';

export const styles = StyleSheet.create({
  container: {
    backgroundColor: 'rgba(54,54,54,0.7)',
    width: '100%',
    height: '100%',
    flex: 1,
  },
  scrollView: {
    flex: 1,
    width: '100%',
    flexGrow: 1,
    justifyContent: 'center',
  },
  addFile: {
    alignSelf: 'center',
    borderRadius: 10,
    backgroundColor: whiteThemeColors.white,
    width: '60%',
    flexDirection: 'row',
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cameraBtn: {
    alignSelf: 'center',
    marginTop: 15,
    borderRadius: 10,
    backgroundColor: whiteThemeColors.white,
    width: '60%',
    flexDirection: 'row',
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cameraText: {
    marginLeft: 10,
    paddingLeft: 0,
    textAlign: 'left',
    color: whiteThemeColors.primary,
    fontFamily: CommonStyles.fonts.semiBold,
  },
  photoBtn: {
    alignSelf: 'center',
    marginTop: 15,
    borderRadius: 10,
    width: '60%',
    backgroundColor: whiteThemeColors.white,
    flexDirection: 'row',
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  photoTxt: {
    marginLeft: 10,
    paddingLeft: 0,
    textAlign: 'left',
    color: whiteThemeColors.primary,
    fontFamily: CommonStyles.fonts.semiBold,
  },
  selectedFileContainer: {
    marginTop: 15,
    marginBottom: 15,
    padding: 10,
  },
  uploadBtn: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'flex-end',
  },
  modalPage: {
    flexDirection: 'column',
    alignContent: 'center',
    alignSelf: 'center',
    borderRadius: 30,
    width: '90%',
    backgroundColor: whiteThemeColors.background,
    paddingBottom: 15,
  },
  modalHeader: {
    width: '100%',
    flexDirection: 'row',
    borderTopLeftRadius: 10,
    borderTopRightRadius: 15,
    alignItems: 'center',
    height: 50,
    paddingRight: 10,
    // justifyContent: 'space-between',
    overflow: 'hidden',
  },
  headerText: {
    width: '95%',
    paddingLeft: 20,
    fontSize: 16,
    borderRadius: 26,

    paddingTop: Platform.OS == 'android' ? 0 : 25,
    textAlignVertical: 'bottom',
    overflow: 'hidden',
    color: whiteThemeColors.primary,
    fontFamily: CommonStyles.fonts.bold,
  },
  CancleTimeViewButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    backgroundColor: CommonStyles.themeClr.backgroundColor,
    borderRadius: 10,
    marginRight: 20,
    height: 35,
    width: '30%',
    marginBottom: 8,
  },
});
