import { StyleSheet } from 'react-native';
import { whiteThemeColors } from '../theme';

const ddStyles = StyleSheet.create({
  ddOverly: {
    width: '100%',
    height: '100%',
    position: 'absolute',
    top: 0,
    left: 0,
    backgroundColor: whiteThemeColors.transparent,
    // zIndex: 50,
  },
  ddContainer: {
    position: 'relative',
    width: 200,
    minHeight: 40,
    maxHeight: 300,
    zIndex: 52,
    backgroundColor: whiteThemeColors.background,
    display: 'flex',
    borderColor: whiteThemeColors.greyLite,
    borderWidth: 0,
    borderStyle: 'solid',
    shadowColor: whiteThemeColors.transparent,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.4,
    shadowRadius: 9,
    elevation: 1,
  },
  ddContainer1: {
    position: 'relative',
    width: 200,
    height: 40,
    maxHeight: 300,
    zIndex: 52,
    backgroundColor: whiteThemeColors.background,
    display: 'flex',
    borderColor: whiteThemeColors.greyLite,
    borderWidth: 2,
    borderStyle: 'solid',
    shadowColor: whiteThemeColors.shadowColor,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.4,
    shadowRadius: 9,
    elevation: 1,
  },
  triangle: {
    width: 0,
    height: 0,
    backgroundColor: whiteThemeColors.transparent,
    borderStyle: 'solid',
  },
  arrowUp: {
    borderTopWidth: 0,
    borderRightWidth: 30,
    borderBottomWidth: 30,
    borderLeftWidth: 30,
    borderTopColor: whiteThemeColors.transparent,
    borderRightColor: whiteThemeColors.transparent,
    borderBottomColor: whiteThemeColors.transparent,
    borderLeftColor: whiteThemeColors.transparent,
  },
  arrowRight: {
    borderTopWidth: 30,
    borderRightWidth: 0,
    borderBottomWidth: 30,

    borderTopColor: whiteThemeColors.transparent,
    borderRightColor: whiteThemeColors.transparent,
    borderBottomColor: whiteThemeColors.transparent,
  },
  arrowDown: {
    borderTopWidth: 30,
    borderRightWidth: 30,
    borderBottomWidth: 0,
    borderLeftWidth: 30,
    borderTopColor: 'tomato',
    borderRightColor: whiteThemeColors.transparent,
    borderBottomColor: whiteThemeColors.transparent,
    borderLeftColor: whiteThemeColors.transparent,
  },
  arrowLeft: {
    borderTopWidth: 30,
    borderBottomWidth: 30,
    borderLeftWidth: 0,
    borderTopColor: whiteThemeColors.transparent,
    borderRightColor: 'tomato',
    borderBottomColor: whiteThemeColors.transparent,
    borderLeftColor: whiteThemeColors.transparent,
  },
  arrowUpLeft: {
    borderTopWidth: 30,

    borderBottomWidth: 0,
    borderLeftWidth: 0,
    borderTopColor: 'tomato',
    borderRightColor: whiteThemeColors.transparent,
    borderBottomColor: whiteThemeColors.transparent,
    borderLeftColor: whiteThemeColors.transparent,
  },
  arrowUpRight: {
    borderTopWidth: 0,

    borderBottomWidth: 30,
    borderLeftWidth: 0,
    borderTopColor: whiteThemeColors.transparent,
    borderRightColor: 'tomato',
    borderBottomColor: whiteThemeColors.transparent,
    borderLeftColor: whiteThemeColors.transparent,
  },
  arrowDownLeft: {
    borderTopWidth: 30,
    borderRightWidth: 0,
    borderBottomWidth: 0,

    borderTopColor: whiteThemeColors.transparent,
    borderRightColor: whiteThemeColors.transparent,
    borderBottomColor: whiteThemeColors.transparent,
  },
  arrowDownRight: {
    borderTopWidth: 0,
    borderRightWidth: 0,
    borderBottomWidth: 30,

    borderTopColor: whiteThemeColors.transparent,
    borderRightColor: whiteThemeColors.transparent,
    borderBottomColor: 'tomato',
    borderLeftColor: whiteThemeColors.transparent,
  },
  offlineContainer: {
    backgroundColor: whiteThemeColors.red,
    height: 30,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    width: '100%',
    position: 'absolute',
    top: 30,
  },
  offlineText: { color: whiteThemeColors.white },
});
export default ddStyles;
