import { Platform, StyleSheet } from 'react-native';
import CommonStyles from 'screens/CommonStyles';
import { whiteThemeColors } from 'utilities';

export const styles = StyleSheet.create({
  listViewContainer: {
    paddingBottom: 2,
    paddingHorizontal: 1,
    backgroundColor: 'white',
  },
  textBtn: {
    borderBottomColor: whiteThemeColors.black + '15',
    shadowColor: whiteThemeColors.black,
    justifyContent: 'flex-start',
    borderBottomWidth: 0.5,
    flexDirection: 'row',
    alignItems: 'center',
    shadowOpacity: 0.1,
    width: '100%',
    marginTop: 10,
    height: 50,
    elevation: 5,
    borderWidth: 0.5,
    borderTopWidth: 0,
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowRadius: 4,
  },
  text: {
    paddingVertical: 4,
    paddingHorizontal: 10,
  },
  safeViewWhite: {
    flex: 1,
    backgroundColor: whiteThemeColors.background,
  },
  headText: {
    fontFamily: CommonStyles.fonts.semiBold,
    paddingBottom: 20,
    color: whiteThemeColors.primary,
  },
  enrollText: {
    fontFamily: CommonStyles.fonts.semiBold,
    borderBottomWidth: 0.5,
    paddingRight: 20,
    paddingBottom: 2,
    borderColor: whiteThemeColors.white,
    borderBottomLeftRadius: 2,
    alignSelf: 'flex-start',
    color: whiteThemeColors.greyDark,
  },
  headView: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-evenly',
    elevation: 5,
    backgroundColor: whiteThemeColors.white,
    marginTop: 20,
    // backgroundColor: 'red',
  },
  gradientView: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-evenly',
    paddingVertical: 30,
    backgroundColor: whiteThemeColors.white,
    width: '100%',
    height: '100%',
    paddingHorizontal: 10,
  },
  nextBtnView: {
    position: 'absolute',
    bottom: 25,
    right: 0,
    flexDirection: 'row',
    alignItems: 'center',
  },
  backBtnView: {
    position: 'absolute',
    bottom: 25,
    left: 0,
    flexDirection: 'row',
    alignItems: 'center',
  },
  ex_flatList: {
    width: '96%',
    alignSelf: 'center',
    zIndex: 1,
    elevation: 3,
    borderRadius: 5,
    overflow: 'hidden',
  },
  ex_listopenIcon: {
    position: 'absolute',
    top: Platform.OS == 'android' ? 0 : 15,
    right: 15,
    bottom: 0,
    textAlignVertical: 'center',
    fontSize: 17,
    paddingHorizontal: 5,
    color: whiteThemeColors.greyDark,
  },
  ex_listValue: {
    color: whiteThemeColors.greyDark,
    fontSize: 16,
  },
  ex_listOpenContainer: {
    width: '100%',
    height: '100%',
    backgroundColor: whiteThemeColors.white,
    borderRadius: 10,
    justifyContent: 'space-between',
    alignItems: 'center',
    flexDirection: 'row',
    marginBottom: 0,
    maxWidth: '100%',
    maxHeight: 150,
  },
  textContainer: {
    paddingRight: 50,
    paddingLeft: 15,
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',

    color: whiteThemeColors.greyDark,
    fontFamily: CommonStyles.fonts.regular,
  },
  ex_listcontainer: {
    marginTop: 10,
    marginBottom: 20,
    padding: 5,
    width: '98%',
    alignSelf: 'center',
  },
  noFoundTxtView: {
    justifyContent: 'center',
    // position: 'absolute',
    alignItems: 'center',
    marginTop: 40,
    // bottom: 0,
    // right: 0,
    // left: 0,
    // top: 0,
  },
  noFoundTxt: {
    marginTop: 5,

    fontFamily: CommonStyles.fonts.medium,
    color: whiteThemeColors.greyDark,
  },
  container: {
    paddingHorizontal: 25,
    paddingTop: 30,
    flex: 1,
  },
  animatedView: {
    top: Platform.OS == 'android' ? 60 : 0,
    position: Platform.OS == 'android' ? 'absolute' : 'relative',
    marginTop: Platform.OS == 'android' ? 0 : -10,
  },
  contentContainer: {
    flex: 1,
    paddingBottom: 100,
  },
});
