import { Platform, StyleSheet } from 'react-native';
import CommonStyles from '../../../../../CommonStyles';
import { whiteThemeColors } from '../../../../../../Utilities';

export const styles = StyleSheet.create({
  modalHeader: {
    width: '100%',
    backgroundColor: whiteThemeColors.primary,
    paddingVertical: 20,
    height: Platform.OS == 'ios' ? 90 : 60,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalHeaderText: {
    marginTop: Platform.OS == 'ios' ? 20 : 0,
    fontSize: 19,
  },
  effectiveDateButton: {
    width: 45,
    height: 45,
    justifyContent: 'center',
    marginHorizontal: 1,
    borderRadius: 30,
    backgroundColor: whiteThemeColors.white,
    marginRight: 10,
    marginTop: 2.5,
  },
  inputViewStyle: {
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  inputLabelStyle: {
    color: whiteThemeColors.textColor.themeColorText,
    width: '90%',
    marginVertical: 10,
  },
  inputStyle: {
    flex: 1,
    width: '100%',
    borderLeftWidth: 1,
    borderRightWidth: 1,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: whiteThemeColors.greyLite,
    borderRadius: 40,
    paddingLeft: 10,
    paddingVertical: 0,
    alignItems: 'flex-start',
    flexDirection: 'row',
  },
  addWageButton: {
    width: '45%',
    height: 40,
    justifyContent: 'center',
    marginHorizontal: 10,
    borderRadius: 20,
  },
  addWageButtonDisabled: {
    width: '45%',
    height: 40,
    justifyContent: 'center',
    marginHorizontal: 10,
    borderRadius: 20,
  },
  weekDayButton: {
    width: 45,
    height: 45,
    // elevation: 0,
    marginHorizontal: 3,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: whiteThemeColors.white + 90,
    borderRadius: 10,
  },
  weekDayButtonText: {
    color: whiteThemeColors.greyDark,
    fontSize: 13,
    fontFamily: CommonStyles.fonts.medium,
  },
  selectedDayButton: {
    width: 45,
    height: 45,
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: 3,
    backgroundColor: whiteThemeColors.primary,
    borderRadius: 10,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 1.84,
    elevation: 3,
  },
  selectedDayButtonText: {
    color: whiteThemeColors.white,
    fontSize: 15,
    fontFamily: CommonStyles.fonts.semiBold,
  },
  fieldContainer: {
    marginTop: 20,
    width: '100%',
    alignItems: 'flex-start',
    justifyContent: 'center',
  },
  fieldTextContainer: {
    width: '90%',
    marginLeft: 5,
    alignItems: 'flex-start',
    justifyContent: 'center',
  },
  fieldText: {
    fontSize: 12,
    color: whiteThemeColors.primaryTextColor,
    fontWeight: 'bold',
  },
  fieldInputContainer: {
    flexDirection: 'row',
    marginTop: 5,
    width: '100%',
    paddingLeft: 15,
    paddingRight: 15,
    fontSize: 15,
    color: whiteThemeColors.greyDark,
    height: 40,
    borderRadius: 20,
    marginBottom: 2,
    alignItems: 'center',
    borderTopWidth: 0.75,
    borderBottomWidth: 0.75,
    borderLeftWidth: 0.75,
    borderRightWidth: 0.75,
    borderColor: whiteThemeColors.greyDark,
    zIndex: 10,
  },
  buttonStyle: {
    justifyContent: 'center',
    alignItems: 'center',
    width: 50,
    height: 50,
    marginTop: 10,
    borderColor: whiteThemeColors.purple2,
    ...Platform.select({
      ios: {},
      android: {
        shadowColor: whiteThemeColors.black,
        shadowOffset: {
          width: 10,
          height: 10,
        },
        shadowOpacity: 1,
        elevation: 7,
        shadowRadius: 20,
      },
    }),
    marginHorizontal: 5,
    zIndex: 100,
  },
  headText: {
    color: whiteThemeColors.black,
    fontSize: 14,
    fontFamily: CommonStyles.fonts.medium,
  },
  timeText: {
    color: whiteThemeColors.greyDark,
    fontFamily: CommonStyles.fonts.regular,
    fontSize: 13,
  },
  buttonSave: {
    width: '100%',
    height: 45,
    backgroundColor: whiteThemeColors.primary,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  buttonText: {
    fontSize: 14,
    fontFamily: CommonStyles.fonts.semiBold,

    color: whiteThemeColors.white,
  },
  modalContainer: {
    width: '80%',
    alignSelf: 'center',
    ...CommonStyles.shadow,
    borderRadius: 5,
  },
  modalPlaceHolderTxt: {
    fontSize: 15,
    color: whiteThemeColors.greyDark,
  },
  modalSingleItemContainer: {
    flexDirection: 'row',
    marginTop: 5,
    marginBottom: 5,
    alignItems: 'center',
  },

  mainContainer: {
    flex: 1,
    backgroundColor: whiteThemeColors.background,
  },
  subContainer: {
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: whiteThemeColors.modalWhiteBG,
  },
  daysNameContainer: { flexDirection: 'row', marginTop: 20 },
  singleDayCircleContainer: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  dateTimesRowContainer: {
    width: '90%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 20,
    marginHorizontal: 20,
  },
  applyItemContainer: { marginTop: 20 },
  applyItemLabel: { paddingHorizontal: 5 },
  wagesListContainer: {
    // flexDirection: 'row',
    // justifyContent: 'space-between',
    borderColor: whiteThemeColors.greyDark,
    marginTop: 10,
    // paddingHorizontal: 5,
    backgroundColor: whiteThemeColors.white + 10,
    // alignItems: 'center',
    borderRadius: 10,
    // height: 45,
    // borderWidth: 0.75,
  },
  descripContainer: {
    width: '100%',
    height: 100,
    marginTop: 10,
    borderRadius: 20,
  },
  descripTxtInp: {
    width: '100%',
    backgroundColor: whiteThemeColors.white + 90,
    padding: 20,
    borderRadius: 15,
    height: 90,
  },
  reviewModalContainer: {
    marginTop: 15,
    borderBottomWidth: 0,
    marginBottom: 20,
    justifyContent: 'center',
    flexDirection: 'row',
  },

  modalListSingleItemContainer: {
    width: '100%',
    flexDirection: 'row',
    marginVertical: 10,
    marginHorizontal: 5,
    alignItems: 'center',
  },
  modalSingleItemTxt: {
    color: whiteThemeColors.lightBlack,
    fontSize: 16,
    textTransform: 'capitalize',
  },
  selectedItemTxt: {
    color: whiteThemeColors.lightBlack,
    fontSize: 16,
    textTransform: 'capitalize',
    width: '100%',
  },
});
