export default [
    [
        [{
            Text:"1",
            value:1,
            cstmClass:""
        },
        {
            Text:"2",
            value:2,
            cstmClass:""
        },
        {
            Text:"3",
            value:3,
            cstmClass:""
        }],
        [{
            Text:"4",
            value:4,
            cstmClass:""
        },
        {
            Text:"5",
            value:5,
            cstmClass:""
        },
        {
            Text:"6",
            value:6,
            cstmClass:""
        }],
        [{
            Text:"7",
            value:7,
            cstmClass:""
        },
        {
            Text:"8",
            value:8,
            cstmClass:""
        },
        {
            Text:"9",
            value:9,
            cstmClass:""
        }],
        [{
            Text:"Clear",
            value:-1,
            cstmClass:""
        },
        {
            Text:"0",
            value:0,
            cstmClass:""
        },
        {
            Text:"Delete",
            value:-2,
            cstmClass:""
        }],
        
  ]
]
  