import { Dimensions, StyleSheet } from 'react-native';
import { whiteThemeColors } from '../../../Utilities';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: 'column',
    backgroundColor: 'black',
  },
  closeIcon: {
    position: 'absolute',
    left: 20,
    top: 40,
    borderColor: whiteThemeColors.greyDark,
    borderWidth: 1,
    padding: 5,
    borderRadius: 25,
    zIndex: 5,
  },
  preview: {
    width: '100%',
    height: '100%',
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  cameraView: {
    flexDirection: 'row',
    position: 'absolute',
    left: Dimensions.get('window').width / 2.3,
    top: -(Dimensions.get('window').height - 180),
    justifyContent: 'center',
    alignItems: 'center',
  },
  captureBtn: {
    borderColor: whiteThemeColors.white,
    borderRadius: 30,
    borderWidth: 2,
    height: 60,
    width: 60,
    alignSelf: 'center',
    marginBottom: 5,
    justifyContent: 'center',
    alignItems: 'center',
  },
  iconBg: {
    height: 50,
    width: 50,
    zIndex: 5,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 25,
  },
  recordVideo: {
    height: 60,
    width: 60,
    padding: 2,
    borderRadius: 30,
    borderWidth: 2,
    borderColor: 'red',
  },
  timerContainer: {
    backgroundColor: whiteThemeColors.red,
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    alignItems: 'center',
    width: 70,
    height: 30,
    borderRadius: 10,
  },
  blinkingDot: {
    backgroundColor: whiteThemeColors.white,
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  timerText: {
    marginLeft: 4,
    fontSize: 14,
    color: whiteThemeColors.white,
  },
  bottomBtns: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    alignItems: 'center',
    height: 70,
    width: '100%',
    backgroundColor: whiteThemeColors.white + 40,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
  },
});
