import { whiteThemeColors } from '../../../../Utilities';
import { StyleSheet } from 'react-native';
import CommonStyles from '../../../CommonStyles';
export const styles = StyleSheet.create({
  Right: {
    marginLeft: 2,
    backgroundColor: whiteThemeColors.purple,
    borderRadius: 10,
    paddingLeft: 1,
    paddingRight: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  TodayTag: {
    color: whiteThemeColors.white,
    fontWeight: '200',
  },
  IsBatch: {
    height: 30,
    alignContent: 'center',
    alignSelf: 'center',
    marginTop: 9,
    borderRadius: 5,
  },
  Border: {
    flex: 10,
    borderStyle: 'solid',
    borderBottomColor: whiteThemeColors.black,
    borderWidth: 1,
    margin: 5,
  },

  RightCancel: {
    alignSelf: 'center',
    alignItems: 'center',
    borderRadius: 5,
  },
  RightBgCancel: {
    paddingBottom: 2,
    backgroundColor: whiteThemeColors.red,
    borderColor: whiteThemeColors.primary,
    borderWidth: 1,
  },
  RightBgUndo: {
    paddingLeft: 4,
    paddingRight: 4,
    paddingBottom: 2,
    backgroundColor: whiteThemeColors.purpleLite,
    borderColor: whiteThemeColors.cyan,
    borderWidth: 1,
    alignItems: 'center',
  },
  cancelClass: {
    fontWeight: '100',
    padding: 5,
    paddingTop: 0,
    marginLeft: 0,
    marginRight: 0,
    paddingBottom: 0,
  },
  makeupToday: {
    color: whiteThemeColors.white,
    fontSize: 10,
    fontWeight: '400',
    paddingLeft: 3,
    paddingRight: 3,
    paddingTop: 1,
  },
  makeupBg: {
    backgroundColor: whiteThemeColors.greenLite,
  },
  todayBg: {
    paddingBottom: 2,
    borderColor: whiteThemeColors.greyLite,
    borderWidth: 1,
    backgroundColor: whiteThemeColors.green,
  },
  cardComponent: {
    flexDirection: 'row',
    width: '95%',
    // backgroundColor: whiteThemeColors.primary + 30,
    alignItems: 'center',
    alignSelf: 'center',
    height: 110,
    borderRadius: 20,
    marginTop: 10,
  },
  container: {
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 6,
    },
    shadowOpacity: 0.35,
    shadowRadius: 1.84,
    elevation: 2,
    // backgroundColor: 'tomato',
  },
  cancelbtn: {
    backgroundColor: whiteThemeColors.red,
    width: '19%',
    height: 20,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 5,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.35,
    shadowRadius: 2.84,
    elevation: 2,
  },
  badgeContainer: {
    width: 16,
    height: 16,
    backgroundColor: whiteThemeColors.primary,

    borderRadius: 4,
    position: 'absolute',
    bottom: -8,
    right: -3,
    justifyContent: 'center',
    alignItems: 'center',
  },
  badgeCount: {
    fontSize: 10,
    color: whiteThemeColors.white,
    // fontFamily: CommonStyles.fonts.universalAppFont2,
  },
  makeup: {
    width: 70,
    height: 20,
    backgroundColor: whiteThemeColors.white,
    position: 'absolute',
    right: 15,
    top: 10,
    borderRadius: 5,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'flex-end',
  },
  container1: {
    height: 30,
    width: 120,
    borderRadius: 5,
    // marginTop: 5,
    flexDirection: 'row',
  },
  makeupTag: {
    width: 70,
    height: 18,
    backgroundColor: 'lightblue',
    borderRadius: 5,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
    marginTop: 5,
  },
  container2: {
    height: 30,
    width: 30,
    borderRadius: 5,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: whiteThemeColors.white + 90,
  },
  container3: {
    height: 30,
    width: 30,
    borderRadius: 5,
    justifyContent: 'center',
    marginLeft: 10,
    alignItems: 'center',
    backgroundColor: whiteThemeColors.white + 90,
  },
  timeTxt: {
    fontFamily: CommonStyles.fonts.semiBold,
    fontSize: 16,
    color: 'gray',
  },
  AmText: {
    fontFamily: CommonStyles.fonts.regular,
    fontSize: 8,
    marginLeft: 5,
    color: 'gray',
  },
  toText: {
    fontSize: 8,
    paddingVertical: 10,
    fontFamily: CommonStyles.fonts.light,
  },
  leftContainer: {
    width: '30%',
    height: 110,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: whiteThemeColors.white + 90,
    borderTopLeftRadius: 10,
    borderBottomLeftRadius: 10,
  },
  centeredView: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  makeupText: {
    color: whiteThemeColors.white,
    fontSize: 10,
    fontFamily: CommonStyles.fonts.semiBold,
  },
  middleContainer: {
    width: '40%',
    height: 110,
    backgroundColor: whiteThemeColors.primary + 30,
    justifyContent: 'center',
    paddingLeft: 10,
  },
  classText: {
    fontFamily: CommonStyles.fonts.regular,
    fontSize: 12,
    color: whiteThemeColors.greyDark,
    marginTop: 3,
  },
  rightContainer: {
    width: '30%',
    height: 110,
    backgroundColor: whiteThemeColors.primary + 30,
    justifyContent: 'center',
    alignItems: 'center',
    borderTopRightRadius: 10,
    borderBottomRightRadius: 10,
  },
});
