import { Platform } from 'react-native';
import { StyleSheet } from 'react-native';
import CommonStyles from 'screens/CommonStyles';
import { whiteThemeColors } from 'utilities';

export const styles = StyleSheet.create({
  title: {
    fontWeight: 'bold',
    // fontSize: 20,
    // color: '#323357',
    textAlign: 'center',
    margin: Platform.OS == 'android' ? 5 : 10,
    fontSize: 18,
    color: whiteThemeColors.primaryTextColor,
  },
  actionIcon: {
    backgroundColor: whiteThemeColors.primary + 30,
    justifyContent: 'center',
    alignItems: 'center',
    width: 20,
    height: 20,
    borderRadius: 4,
    marginTop: -4,
    marginLeft: 3,
  },
  userImage: {
    height: 30,
    width: 30,
    marginTop: 0,
    resizeMode: 'cover',
    borderRadius: 15,
    borderWidth: 0.25,
    borderColor: '#0039ff',
  },
  submitCourseReview: {
    borderRadius: 10,
    padding: 20,
    width: '100%',
    alignSelf: 'center',
    paddingBottom: 140,
  },
  loaderContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    height: '100%',
    backgroundColor: whiteThemeColors.background,
  },
  mainContainer: {
    height: '100%',
    backgroundColor: whiteThemeColors.background,
    paddingTop: 20,
  },
  commentSectionContainer: {
    backgroundColor: whiteThemeColors.primary + 10,
    borderRadius: 10,
    marginVertical: 10,
    paddingTop: 10,
    width: '100%',
    shadowColor: whiteThemeColors.shadowColor,
  },
  userNameTxt: {
    fontSize: 13,

    color: whiteThemeColors.primaryTextColor,
    fontFamily: CommonStyles.fonts.semiBold,
  },
  singleCommentContainer: {
    marginLeft: 7,
    marginTop: 8,
    backgroundColor: whiteThemeColors.white + 90,
    borderRadius: 7,
    padding: 10,
    width: '75%',
    borderColor: whiteThemeColors.primary,
    borderTopLeftRadius: 0,
  },
  commentFooterContainer: {
    justifyContent: 'center',
    flexDirection: 'row',
    height: 20,
    marginTop: 10,
  },
  dateTxt: {
    fontSize: 10,
    color: whiteThemeColors.lightBlack,
    fontFamily: CommonStyles.fonts.light,
  },
  likeCountTxt: {
    fontSize: 10,
    marginLeft: 5,
    alignSelf: 'auto',
    color: whiteThemeColors.black,
    fontFamily: CommonStyles.fonts.light,
  },
  cmtReplyTxt: {
    fontSize: 10,
    marginLeft: 5,
    alignSelf: 'auto',
    color: whiteThemeColors.black,
    fontFamily: CommonStyles.fonts.regular,
  },
  replyingUserNameTxt: {
    fontSize: 13,
    alignSelf: 'flex-end',
    marginHorizontal: 2,
    color: whiteThemeColors.primary,
    fontFamily: CommonStyles.fonts.semiBold,
  },
  commentReplyContainer: {
    marginRight: 7,
    marginTop: 8,
    backgroundColor: whiteThemeColors.chatInterface.chatRight,
    borderRadius: 7,
    padding: 10,
    width: '75%',
    borderTopRightRadius: 0,
    borderColor: whiteThemeColors.primary,
    alignSelf: 'flex-end',
  },
  replyingFooterContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    height: 30,
    marginTop: 10,
  },
  replyingDateTxt: {
    width: Platform.OS == 'android' ? 140 : 160,
    fontSize: 10,
    color: whiteThemeColors.lightBlack,
    marginLeft: 7,
    fontFamily: CommonStyles.fonts.light,
  },
  noDisccusionTxt: {
    marginTop: 300,
    alignSelf: 'center',
    fontSize: 18,
    fontWeight: '500',
    color: whiteThemeColors.primary,
    fontFamily: CommonStyles.fonts.regular,
  },
});
