import { Platform, StyleSheet } from 'react-native';
import CommonStyles from 'screens/CommonStyles';
import { whiteThemeColors } from 'utilities';

export const styles = StyleSheet.create({
  cardContainer: {
    width: '94%',
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
    borderRadius: 20,
    backgroundColor: whiteThemeColors.white + 90,
    paddingVertical: 7,
    marginTop: 8,
  },
  // cardContainer: {
  //   width: '91%',
  //   alignSelf: 'center',
  //   justifyContent: 'center',
  //   alignItems: 'center',
  //   overflow: 'hidden',
  //   borderRadius: 10,
  //   backgroundColor: whiteThemeColors.white,
  //   paddingVertical: 4,
  //   marginVertical: 8,
  // },
  floatingIcon: {
    fontSize: 120,
    position: 'absolute',
    right: -10,
    top: -10,
    color: whiteThemeColors.primaryDark,
    opacity: 0.1,
  },
  innerContainer: {
    alignItems: 'center',
    paddingVertical: 15,
    paddingHorizontal: 15,
    width: '100%',
    borderRadius: 15,

    overflow: Platform.OS == 'android' ? 'hidden' : 'visible',
  },
  headerText: {
    fontSize: 16,
    color: whiteThemeColors.primaryTextColor,
    fontFamily: CommonStyles.fonts.semiBold,
    textTransform: 'capitalize',
    paddingTop: 12,
  },
  assessmentToggleContainer: {
    flexDirection: 'row',
    width: '100%',
    paddingBottom: 20,
    alignItems: 'flex-end',
  },
  assessmentToggleDetailsContainer: {
    flexDirection: 'row',
    paddingTop: 5,
    width: '47%',
  },
  assessmentTotalTimeContainer: {
    alignSelf: 'flex-start',
    marginHorizontal: 10,
  },
  labelText: {
    fontSize: 12,
    color: whiteThemeColors.primary,

    fontFamily: CommonStyles.fonts.semiBold,
  },
  totalTimeLabel: {
    marginBottom: 5,
  },
  timeView: {
    borderRadius: 5,
    paddingHorizontal: 15,
    paddingLeft: 0,
    paddingVertical: 5,
    // backgroundColor: whiteThemeColors.primary + 10,
    // elevation: 5,
  },
  timeText: {
    fontSize: 12,
    color: whiteThemeColors.black,
    // paddingHorizontal: 10,
    fontFamily: CommonStyles.fonts.semiBold,
  },
  assessmentCardClockIconContainer: { paddingBottom: 4 },
  assessmentTimeTakenContainer: {
    width: '50%',
    flexDirection: 'row',
    paddingTop: 5,
    paddingLeft: 10,
  },
  assessmentTimeTakenSubContainer: {
    alignSelf: 'flex-start',
    marginHorizontal: 10,
  },
  CardToggleIconContainer: {
    position: 'absolute',
    right: 25,
    zIndex: 1,
    backgroundColor: whiteThemeColors.primary + 30,
    borderRadius: 12,
    width: 35,
    height: 35,
    justifyContent: 'center',
    alignItems: 'center',
    top: 20,
  },
  timeTakenLabel: { marginBottom: 5 },
  circle2: {
    position: 'absolute',
    height: 100,
    width: 100,
    borderRadius: 50,
    bottom: 10,
    left: '80%',
    backgroundColor: whiteThemeColors.greyDark + '06',
  },
  circle3: {
    position: 'absolute',
    height: 150,
    width: 150,
    borderRadius: 80,
    top: -50,
    left: -30,
    backgroundColor: whiteThemeColors.primaryDark + '08',
  },
});
