import { Dimensions, StyleSheet } from 'react-native';
import { isTablet } from 'react-native-device-info';
import CommonStyles from '../../../../../../../CommonStyles';
import { whiteThemeColors } from '../../../../../../../../Utilities';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: whiteThemeColors.background,
    width: '100%',
  },
  scrollView: {
    flex: 1,
    paddingTop: 10,
  },
  flatListContainer: {
    // flexDirection: 'row',
    // flexWrap: 'wrap',
    // alignItems: 'center',
    // padding: 5,
    paddingHorizontal: 10,
  },
  singleCard: {
    alignSelf: 'center',
    justifyContent: 'space-between',
    width: '50%',
    paddingHorizontal: 5,
  },
  subContainer: {
    width: isTablet() ? 175 : 170,
    height: isTablet() ? 170 : 168,
    borderRadius: 20,
    backgroundColor: whiteThemeColors.primary + 30,
    shadowColor: whiteThemeColors.greyDark,
  },
  btnDownload: {
    position: 'absolute',
    bottom: 5,
    right: 5,
    height: 20,
    width: 20,
    zIndex: 10,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 5,
    backgroundColor: whiteThemeColors.white + 90,
  },
  containerWithTxtIcon: {
    marginTop: 10,
    marginBottom: 7,
    width: 80,
    height: 80,
    borderRadius: 20,
    backgroundColor: whiteThemeColors.white,
    justifyContent: 'center',
    alignItems: 'center',
  },
  txtContainer: {
    position: 'absolute',
    top: 7,
    bottom: 0,
    right: 0,
    left: 0,
    zIndex: 1000,
    justifyContent: 'center',
    alignItems: 'center',
  },
  labelTxt: {
    fontSize: 12,
    color: whiteThemeColors.primary + '90',
  },
  fileNameTxt: {
    fontSize: 11,
    textTransform: 'capitalize',
    fontWeight: '400',
    // fontFamily: CommonStyles.fonts.universalAppFont,
    paddingRight: 30,
    paddingLeft: 15,
  },
  emptyListContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    alignSelf: 'center',
  },
  emptyListTxt: {
    marginTop: 200,
    fontFamily: CommonStyles.fonts.medium,
    color: whiteThemeColors.greyDark,
  },
  close: {
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    borderRadius: 5,
    zIndex: 10,
    height: 20,
    width: 20,
    right: 5,
    top: 5,
    backgroundColor: whiteThemeColors.white + 90,
  },
  title: {
    padding: 20,

    fontSize: 18,
    textAlign: 'left',
    color: whiteThemeColors.primary,
    fontFamily: CommonStyles.fonts.semiBold,
  },
  addFileCont: {
    justifyContent: 'center',
    position: 'absolute',
    alignSelf: 'center',
    zIndex: 10,
    height: 55,
    bottom: 10,
    right: 10,
    width: 55,
  },
  addFileBtn: {
    backgroundColor: whiteThemeColors.primary,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 27.5,
    height: '100%',
    width: '100%',
  },
  itemContainer: {
    width: 'auto',
    height: 130,
    borderRadius: 15,
    backgroundColor: whiteThemeColors.primary + 20,

    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 5,
  },
  deleteContainer: {
    width: 20,
    height: 20,
    position: 'absolute',
    right: 10,
    top: 8,
    backgroundColor: whiteThemeColors.white + 90,
    borderRadius: 5,
    justifyContent: 'center',
    alignItems: 'center',
  },
  downloadContainer: {
    width: 20,
    height: 20,
    position: 'absolute',
    right: 10,
    bottom: 10,
    backgroundColor: whiteThemeColors.white + 90,
    borderRadius: 5,
    justifyContent: 'center',
    alignItems: 'center',
  },
  fileNameText: {
    color: whiteThemeColors.black + 90,
    fontSize: 10,
    fontFamily: CommonStyles.fonts.regular,
    width: 100,
    textAlign: 'center',
  },
  fileSizeText: {
    color: whiteThemeColors.greyDark,
    fontSize: 11,
  },

  fileIconContainer: {
    marginTop: 7,
    marginBottom: 7,
    width: 65,
    height: 65,
    borderRadius: 20,
    backgroundColor: whiteThemeColors.white,
    justifyContent: 'center',
    alignItems: 'center',
  },
  filetxtContainer: {
    position: 'absolute',
    top: 7,
    bottom: 0,
    right: 0,
    left: 0,
    zIndex: 1000,
    justifyContent: 'center',
    alignItems: 'center',
  },
  filelabelTxt: {
    fontSize: 8,
    color: whiteThemeColors.primary + '90',
    zIndex: 1000,
    fontFamily: CommonStyles.fonts.regular,
    color: 'white',
  },
});
