import { Platform, StyleSheet } from 'react-native';
import { whiteThemeColors } from '../../../../../../../../Utilities';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(54,54,54,0.3)',
  },
  content: {
    backgroundColor: whiteThemeColors.white,
    width: '100%',
    borderRadius: 35,
    position: 'absolute',
    bottom: 1,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    paddingBottom: 20,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 5,
    borderTopLeftRadius: 35,
    borderTopRightRadius: 35,
    backgroundColor: whiteThemeColors.primary,
  },
  headerText: {
    color: whiteThemeColors.white,
    fontSize: 16,
    fontWeight: '600',
    marginLeft: 30,
    marginTop: 5,
  },
  closeIcon: {
    backgroundColor: whiteThemeColors.white,
    borderRadius: 15,
    zIndex: 10,
    marginRight: 15,
    marginTop: 10,
  },
  rowWrapper: {
    width: '90%',
    padding: 15,
    alignSelf: 'center',
    borderRadius: 10,
    marginTop: 10,
    backgroundColor: whiteThemeColors.primary + 10,
  },
  row: { flexDirection: 'row', alignItems: 'center' },
  keyText: {
    marginLeft: 5,
    fontSize: 12,
  },
  inputStyle: {
    fontSize: 12,
    color: whiteThemeColors.greyDark,
    minWidth: 100,
  },
  submitBtnWrapper: {
    alignSelf: 'flex-end',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    backgroundColor: whiteThemeColors.primary,
    borderRadius: 20,
    width: 100,
    height: 34,
    marginTop: 10,
    marginRight: 30,
    paddingHorizontal: 15,
  },
  submitText: {
    fontWeight: '600',
    color: whiteThemeColors.white,
  },
  submitIconWrapper: {
    backgroundColor: whiteThemeColors.primary,
    width: 20,
    height: 20,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 5,
  },
});
