import { Platform, StyleSheet } from 'react-native';
import CommonStyles from 'screens/CommonStyles';
import { whiteThemeColors } from 'utilities';

export const styles = StyleSheet.create({
  container: {
    backgroundColor: whiteThemeColors.background,
    flex: 1,
    flexGrow: 1,
  },
  cardContainer: {
    width: '100%',
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
    borderRadius: 10,
    backgroundColor: whiteThemeColors.background,
    paddingVertical: 20,
    marginVertical: 8,
  },
  card2: {
    backgroundColor: whiteThemeColors.primary + 20,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingBottom: 10,
  },
  innerContainer: {
    alignItems: 'center',
    marginTop: 10,
    paddingVertical: 15,
    paddingHorizontal: 15,
    width: '90%',
    borderRadius: 20,
    overflow: Platform.OS == 'android' ? 'hidden' : 'visible',
    backgroundColor: whiteThemeColors.white + 90,
  },
  headerText: {
    fontSize: 18,
    paddingLeft: 15,
    marginTop: 10,
    fontFamily: CommonStyles.fonts.bold,
    color: whiteThemeColors.primaryTextColor,
  },
  detailscon: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    borderBottomWidth: 1,
    borderBottomColor: whiteThemeColors.greyLite,
    paddingVertical: 15,
  },
  keyText: {
    fontSize: 12,
    fontFamily: CommonStyles.fonts.medium,
  },
  valueText: {
    fontSize: 12,
    color: whiteThemeColors.greyDark,
    fontFamily: CommonStyles.fonts.regular,
  },
  updateOverview: {
    borderWidth: 1,
    borderColor: whiteThemeColors.primaryDark + 80,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    marginTop: 6,
    borderRadius: 10,
    paddingVertical: 7,
    justifyContent: 'center',
    backgroundColor: whiteThemeColors.primary + 20,
    width: 200,
    alignSelf: 'center',
  },
  updateBtnTxt: {
    color: whiteThemeColors.primaryDark,
    marginLeft: 10,
    fontSize: 12,
    fontFamily: CommonStyles.fonts.semiBold,
  },
  showContactsContainer: {
    alignSelf: 'center',
    alignItems: 'center',
    marginTop: 15,
  },
  inner: {
    width: '100%',
    backgroundColor: whiteThemeColors.white + 90,
    padding: 10,
    borderRadius: 10,
  },
  key: {
    fontFamily: CommonStyles.fonts.regular,
    fontSize: 12,
    color: 'gray',
    marginTop: 10,
  },
  key2: {
    fontFamily: CommonStyles.fonts.regular,
    fontSize: 10,
    color: 'gray',
    marginTop: 10,
  },
  key2Value: { marginTop: 0, color: 'black' },
  value2: {
    fontFamily: CommonStyles.fonts.medium,
    fontSize: 12,
  },
  value: {
    fontFamily: CommonStyles.fonts.medium,
    fontSize: 14,
  },
  week: {
    // width: '100%',
    borderBottomWidth: 1,
    borderBottomColor: whiteThemeColors.greyLite,
    marginTop: 10,
    backgroundColor: whiteThemeColors.primary + 20,
    borderRadius: 10,
    paddingVertical: 10,
    marginBottom: 5,
  },
  seemore: {
    position: 'absolute',
    right: 5,
    bottom: 5,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  seemoreText: {
    fontFamily: CommonStyles.fonts.light,
    fontSize: 10,
    marginRight: 4,
  },
  arrowIcon: {
    width: 20,
    height: 20,
    backgroundColor: whiteThemeColors.primary + 30,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 5,
  },
  fromCont: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginRight: 20,
  },
  fromInn: {
    width: '50%',
    justifyContent: 'flex-start',
  },
  notes: {
    backgroundColor: whiteThemeColors.white + 90,
    borderRadius: 10,
    marginTop: 5,
    padding: 10,
  },
  inst: {
    borderRadius: 5,
    backgroundColor: whiteThemeColors.primary + 90,
    padding: 3,
    marginTop: 5,
    marginLeft: 2,
  },
  staffCon: {
    backgroundColor: whiteThemeColors.white + 90,
    borderRadius: 10,
    marginTop: 2,
    flexDirection: 'row',
    flexWrap: 'wrap',
    padding: 10,
  },
  days: {
    height: 30,
    width: 30,
    borderRadius: 8,
    marginHorizontal: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  edit: {
    width: 50,
    height: 25,
    backgroundColor: whiteThemeColors.primary,
    position: 'absolute',
    right: 1,
    borderTopRightRadius: 10,
    borderBottomLeftRadius: 15,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10,
  },
  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(54,54,54,0.6)',
  },
  crossIcon: {
    backgroundColor: whiteThemeColors.primary + 30,
    borderRadius: 10,
  },
  modalView: {
    width: '100%',
    backgroundColor: whiteThemeColors.background,
    padding: 25,
    paddingTop: 60,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  headerContainer: {
    position: 'absolute',
    top: 35,
    right: 20,
  },
  input: {
    borderRadius: 8,
    width: '100%',
    height: 35,
    backgroundColor: whiteThemeColors.primary + 30,
    paddingLeft: 10,
    marginTop: 3,
    fontSize: 12,
  },
  dropDownContainer: {
    width: 200,
    height: -1,
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
  dropdownStyle: {
    width: 200,
    marginTop: 10,
    borderRadius: 10,
    numberOfLines: 1,
  },
  dropDownTxt: {
    marginLeft: 5,
    width: 200,
    color: whiteThemeColors.black,
    fontSize: 13,
  },
  statusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    alignSelf: 'center',
    marginHorizontal: 5,
  },
  classTiming: {
    fontSize: 10,
    fontFamily: CommonStyles.fonts.medium,
    color: whiteThemeColors.white
  },
  classTimingValue: {
    fontSize: 13,
    fontFamily: CommonStyles.fonts.medium,
    color: whiteThemeColors.black,
    marginTop: 5
  },
  staffName: {
    fontSize: 10,
    marginLeft: 5,
    color: whiteThemeColors.white,
  }
});
