export const Constants = {
  Enrollment: 'Enrollment',
  Fee: 'Fee',
  Tabs: ['Enrollment', 'Fee'],
  OrginalAmount: 'Orignal Amount',
  DiscountAmount: 'Discount Amount',
  FeeAmount: 'Fee Amount',
  TotalAmount: 'Total Amount',
  BillingCycle: 'Billing Cycle',
  RequestedBy: 'Requested By',
  Pay: 'Pay',
  StudentFee: 'Student Fee',
  AutoDeduct: 'Auto Deduct',
  NoPaymentFound: 'No Payments Found',
  PaymentDetails: 'Payment Details',
  CourseLevel: 'Course/Level',
  ClassName: 'Class Name',
  EventName: 'Event Name',
  EventTiming: 'Event Timing',
  NextScheduleDate: 'Next Schedule Date',
  ProcessPayment: 'Process Payment',
  Proceed: 'Proceed',
  Cancel: 'Cancel',
  FooterNote:
    'Payment information available on file. Click on Proceed to Process the Payment.',
  Okay: 'Okay',
  Error: 'Error',
  Yes: 'Yes',
  No: 'No',
  Balance: 'Total Balance',
  TotalAmountDue: ' Total Amount Due',
  ManualRecurring: 'Manual Recurring',
  ScheduledRecurring: 'Scheduled Recurring',
  Unpaid: 'Unpaid',
  Coupon: 'Coupon',
  Action: 'Action',
  AddCoupon: 'Add Coupon',
  AvailableBalance: 'Avail. Balance',
  TotalAmountDue: 'Total Amount Due',
  Status: 'Status',
  ApplyCoupon: 'Apply Coupon',
  InsertCoupon: 'Insert Coupon',
  Apply: 'Apply',
  NoCoupon: 'No Coupons Applied',
  PleaseEnterAValidCoupon: 'Please enter a valid coupon',
  SelectStudent: 'Select Student',
  GridTypeEnum: { Payments: 'payments', Fees: 'fees' },
};
