import {
  englishSideBar,
  englishStudentSideBar,
  englishCompanyCodeScreen,
  englishGetStartedScreen,
  englishLoginScreen,
  englishDashboardScreen,
  englishCourseScreen,
  englishCourseContentScreen,
  englishMessageScreen,
  englishReportsScreen,
  englishStudentProgressScreen,
  englishStudentProgressReportScreen,
  englishStudentAssessmentScreen,
  englishStudentAssessmentReportScreen,
  englishAttendenceMarkingDateWiseScreen,
  englishViewbyClass,
  englishDateList,
  englishPincodeScreen,
  englishIndividualScreen,
  englishGroupScreen,
  englishNotificationScreen,
  englishTrackerScreen,
  englishAddWages,
  englishWagesDetial,
  englishAdminSchedule,
  englishScheduleWeekView,
  englishTimesheet,
  englishCourseContent,
  englishNoteScreen,
  englishOnlineClassScreen,
  englishClassDetialScreen,
  englishClassTabScreen,
  englishLoaderScreen,
  englishSubmittingButton,
  englishTimeSheetDetial,
  englishTimeOffScreen,
  englishAddTimeOff,
  englishApprovel,
  englishAddorEdit,
  englishCommonWords,
  englishClassHeading,
  englishClassMenu,
  englishStoreScreen,
} from '../screens/Strings/english';
import {
  arabicSideBar,
  arabicStudentSideBar,
  arabicCompanyCodeScreen,
  arabicGetStartedScreen,
  arabicLoginScreen,
  arabicDashboardScreen,
  arabicCourseScreen,
  arabicCourseContentScreen,
  arabicMessagesScreen,
  arabicReportsScreen,
  arabicStudentProgressScreen,
  arabicStudentProgressReportScreen,
  arabicStudentAssessmentScreen,
  arabicStudentAssessmentReportScreen,
  arabicAttendenceMarkingDateWiseScreen,
  arabicViewbyClass,
  arabicDateList,
  arabicPincodeScreen,
  arabicIndividualScreen,
  arabicGroupScreen,
  arabicNotificationScreen,
  arabicTrackerScreen,
  arabicAddWages,
  arabicWagesDetial,
  arabicAdminSchedule,
  arabicScheduleWeekView,
  arabicTimesheet,
  arabicCourseContent,
  arabicNoteScreen,
  arabicOnlineClassScreen,
  arabicClassDetialScreen,
  arabicClassTabScreen,
  arabicLoaderScreen,
  arabicSubmittingButton,
  arabicTimeSheetDetial,
  arabicTimeOffScreen,
  arabicAddTimeOff,
  arabicApprovel,
  arabicAddorEdit,
  arabicCommonWords,
  arabicClassHeading,
  arabicClassMenu,
} from '../screens/Strings/arabic';

export var languages = {
  english: {
    sideBar: englishSideBar,
    studentSideBar: englishStudentSideBar,
    cmpyCodeScreen: englishCompanyCodeScreen,
    getStartedScreen: englishGetStartedScreen,
    loginScreen: englishLoginScreen,
    dashboardScreen: englishDashboardScreen,
    coursesScreen: englishCourseScreen,
    courseContentScreenAssign: englishCourseContentScreen,
    messageScreen: englishMessageScreen,
    reportScreen: englishReportsScreen,
    studentProgressScreen: englishStudentProgressScreen,
    studentProgressReportScreen: englishStudentProgressReportScreen,
    studentAssessmentScreen: englishStudentAssessmentScreen,
    studentAssessmentReportScreen: englishStudentAssessmentReportScreen,
    markAttendenceDateWiseScreen: englishAttendenceMarkingDateWiseScreen,
    viewByClass: englishViewbyClass,
    classDateList: englishDateList,
    pincodeScreen: englishPincodeScreen,
    individualCheckinScreen: englishIndividualScreen,
    groupCheckinScreen: englishGroupScreen,
    notificationScreen: englishNotificationScreen,
    timeTrackerScreen: englishTrackerScreen,
    addWage: englishAddWages,
    wageDetial: englishWagesDetial,
    adminSchedule: englishAdminSchedule,
    ScheduleWeekView: englishScheduleWeekView,
    timeSheet: englishTimesheet,
    timeSheetDetial: englishTimeSheetDetial,
    timeOff: englishTimeOffScreen,
    addTimeOffScreen: englishAddTimeOff,
    approvelsScreen: englishApprovel,
    courseContentScreen: englishCourseContent,
    classNotesScreen: englishNoteScreen,
    onlineClass: englishOnlineClassScreen,
    classDetialScreen: englishClassDetialScreen,
    classTab: englishClassTabScreen,
    loaderScreen: englishLoaderScreen,
    submittButton: englishSubmittingButton,
    addOrEdit: englishAddorEdit,
    commonWords: englishCommonWords,
    classListHeading: englishClassHeading,
    classMenu: englishClassMenu,
    storeScreen: englishStoreScreen,
  },
  arabic: {
    sideBar: arabicSideBar,
    studentSideBar: arabicStudentSideBar,
    cmpyCodeScreen: arabicCompanyCodeScreen,
    getStartedScreen: arabicGetStartedScreen,
    loginScreen: arabicLoginScreen,
    dashboardScreen: arabicDashboardScreen,
    coursesScreen: arabicCourseScreen,
    courseContentScreenAssign: arabicCourseContentScreen,
    messageScreen: arabicMessagesScreen,
    reportScreen: arabicReportsScreen,
    studentProgressScreen: arabicStudentProgressScreen,
    studentProgressReportScreen: arabicStudentProgressReportScreen,
    studentAssessmentScreen: arabicStudentAssessmentScreen,
    studentAssessmentReportScreen: arabicStudentAssessmentReportScreen,
    markAttendenceDateWiseScreen: arabicAttendenceMarkingDateWiseScreen,
    viewByClass: arabicViewbyClass,
    classDateList: arabicDateList,
    pincodeScreen: arabicPincodeScreen,
    individualCheckinScreen: arabicIndividualScreen,
    groupCheckinScreen: arabicGroupScreen,
    notificationScreen: arabicNotificationScreen,
    timeTrackerScreen: arabicTrackerScreen,
    addWage: arabicAddWages,
    wageDetial: arabicWagesDetial,
    adminSchedule: arabicAdminSchedule,
    ScheduleWeekView: arabicScheduleWeekView,
    timeSheet: arabicTimesheet,
    timeSheetDetial: arabicTimeSheetDetial,
    timeOff: arabicTimeOffScreen,
    addTimeOffScreen: arabicAddTimeOff,
    approvelsScreen: arabicApprovel,
    courseContentScreen: arabicCourseContent,
    classNotesScreen: arabicNoteScreen,
    onlineClass: arabicOnlineClassScreen,
    classDetialScreen: arabicClassDetialScreen,
    classTab: arabicClassTabScreen,
    loaderScreen: arabicLoaderScreen,
    submittButton: arabicSubmittingButton,
    addOrEdit: arabicAddorEdit,
    commonWords: arabicCommonWords,
    classListHeading: arabicClassHeading,
    classMenu: arabicClassMenu,
  },
};
