import { StyleSheet } from 'react-native';
import { hp, wp } from '../../../../../Helpers/Responsiveness';
import CommonStyles from '../../../../CommonStyles';
import { getHeight, getWidth, whiteThemeColors } from 'utilities';

export const styles = StyleSheet.create({
  titleBar: {
    width: '100%',
    alignSelf: 'center',
    borderBottomRightRadius: 25,
    borderBottomLeftRadius: 25,
    height: 48,
    flexDirection: 'row',
    backgroundColor: CommonStyles.themeClr.backgroundColor,
    paddingHorizontal: 10,
    justifyContent: 'center',
    marginBottom: 10,
    alignItems: 'center',
    alignContent: 'center',
  },
  audioPlayer: {
    width: getWidth('100%'),
    height: getHeight(40),
    marginTop: 50,
  },
  audioPlayerIcon: {
    width: getWidth('99%'),
    height: getHeight(45),
    alignSelf: 'center',
    backgroundColor: '#271B4A',
    justifyContent: 'center',
    borderTopRightRadius: 25,
    borderTopLeftRadius: 25,
    shadowColor: whiteThemeColors.black,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 1,
    elevation: 3,
    shadowRadius: 20,
  },
  audioPlayerBar: {
    borderBottomLeftRadius: 25,
    borderBottomRightRadius: 25,
    alignSelf: 'center',
    width: getWidth('99%'),
    height: getHeight(8),
    backgroundColor: whiteThemeColors.AudioChallengeView.mediaControllIconColor,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: whiteThemeColors.black,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 1,
    elevation: 3,
    shadowRadius: 20,
  },
  audioPlayerBarLeft: {
    flex: 0.2,
    height: getHeight(6),
    justifyContent: 'center',
  },
  audioPlayerBarRight: {
    flex: 0.8,
    flexDirection: 'row',
    height: getHeight(6),
    justifyContent: 'center',
  },
  bottomView: {
    width: getWidth('100%'),
    height: getHeight(10),
    marginTop: getHeight(20),
    justifyContent: 'space-evenly',
    alignItems: 'center',
    flexDirection: 'row',
  },
  bottomViewButton: {
    width: getWidth('40%'),
    borderRadius: 30,
    justifyContent: 'center',
    shadowColor: whiteThemeColors.black,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    flexDirection: 'row',
  },
  loading: {
    width: wp(100),
    height: hp(91),
    justifyContent: 'center',
    alignItems: 'center',
  },
  failedText: {
    backgroundColor: whiteThemeColors.red,
    paddingHorizontal: 15,
    paddingVertical: 10,

    color: 'white',
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 10,
    backgroundColor: whiteThemeColors.background,
  },
  leftChevron: {
    marginLeft: 5,
    justifyContent: 'center',
    backgroundColor: whiteThemeColors.primary + 30,
    flexDirection: 'row',
    alignItems: 'center',
    height: 45,
    borderRadius: 10,
  },
  leftChevronIcon: {
    marginLeft: 0,
    marginRight: 0,
    padding: 0,
    backgroundColor: whiteThemeColors.primary + 30,
  },
  previousText: {
    color: whiteThemeColors.black,
    fontFamily: CommonStyles.fonts.medium,
    margin: 0,
    paddingRight: 0,
  },
  markAsComplete: {
    width: '35%',
    justifyContent: 'center',
    backgroundColor: whiteThemeColors.primary + 30,
    shadowColor: whiteThemeColors.black,
    flexDirection: 'row',
    alignItems: 'center',
    height: 45,
  },
  nextButton: {
    marginLeft: 5,
    justifyContent: 'center',
    backgroundColor: whiteThemeColors.primary + 30,
    flexDirection: 'row',
    alignItems: 'center',
    height: 45,
    borderRadius: 10,
  },
  nextText: {
    color: whiteThemeColors.black,
    margin: 0,
    paddingRight: 0,
    fontFamily: CommonStyles.fonts.medium,
  },
});
