import { Platform, StyleSheet } from 'react-native';
import CommonStyles from '../../../CommonStyles';
import { whiteThemeColors } from '../../../../Utilities';

export const styles = StyleSheet.create({
  container: {
    width: '100%',
    paddingLeft: '10%',
    alignItems: 'center',
    // justifyContent: 'center',
    alignSelf: 'center',
  },
  circle1: {
    backgroundColor: whiteThemeColors.primary + '20',
    position: 'absolute',
    zIndex: 2,
    left: 30,
    top: 1,
  },
  circle2: {
    backgroundColor: whiteThemeColors.primary + '20',
    justifyContent: 'center',
    position: 'absolute',
    alignSelf: 'center',
    right: 35,
  },
  nameView: {
    width: '90%',
    alignSelf: 'center',
  },
  clsName: {
    fontSize: 16,
    color: whiteThemeColors.primaryTextColor,
    margin: Platform.OS == 'android' ? 5 : 10,
    fontFamily: CommonStyles.fonts.semiBold,
  },
  bottomContainer: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'flex-end',
  },
  inputContainer: {
    minHeight: 150,
    marginLeft: 7,
    marginRight: 7,
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
    padding: 10,
    paddingLeft: 20,
    borderRadius: 10,
    paddingHorizontal: 5,
    width: '90%',
    backgroundColor: whiteThemeColors.white + 90,
  },
  input: {
    height: 90,
    fontSize: 13,
    borderBottomColor: whiteThemeColors.greyDark,
    fontFamily: CommonStyles.fonts.regular,
  },
  btnContainer: {
    position: 'absolute',
    bottom: 10,
    right: 10,
    flexDirection: 'row',
    width: '100%',
    alignItems: 'center',
    paddingTop: 5,
    marginTop: 5,
  },
  btn: {
    flexDirection: 'row',
    backgroundColor: whiteThemeColors.primary,
    paddingHorizontal: 13,
    paddingVertical: 5,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  clearBtn: {
    flexDirection: 'row',
    backgroundColor: whiteThemeColors.background,
    paddingHorizontal: 13,
    paddingVertical: 5,
    borderRadius: 5,
    justifyContent: 'center',
    alignItems: 'center',
  },
  icon: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  keyboardView: {
    flex: 1,
    // justifyContent: 'center',
    marginTop: 20,
    backgroundColor: 'transparent',
  },
  detailsText: {
    color: whiteThemeColors.greyDark,
    fontFamily: CommonStyles.fonts.light,
    fontSize: 12,
    marginHorizontal: Platform.OS == 'android' ? 5 : 10,
    marginBottom: 20,
  },
});
