import { Platform, StyleSheet } from 'react-native';
import { whiteThemeColors } from '../../../../../Utilities';
import CommonStyles from '../../../../../screens/CommonStyles';
export const styles = StyleSheet.create({
  mainContainer: {
    width: '100%',
    justifyContent: 'center',
  },
  indicatorContainer: {
    flex: 1,
    height: '100%',
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  nodataContainer: {
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    flex: 1,
  },
  nodataTxt: {
    fontSize: 13,
    marginTop: 20,
    color: whiteThemeColors.lightBlack,
  },
  btnContainer: {
    marginTop: -53,
    zIndex: 1,
    flexDirection: 'row',
    justifyContent: 'flex-end',
    marginRight: 40,
  },
  btn: {
    borderRadius: 10,
    height: 35,
    backgroundColor: whiteThemeColors.primary,
    justifyContent: 'center',
  },
  assessmentCardContainer: {
    width: '95%',
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
    borderRadius: 15,
    backgroundColor: whiteThemeColors.white + 90,
    marginVertical: 8,
  },
  infoRow: {
    flexDirection: 'row',
  },
  circle1: {
    position: 'absolute',
    height: 170,
    width: 170,
    borderRadius: 90,
    top: 40,
    left: -80,

    backgroundColor: whiteThemeColors.primary + '07',
  },
  circles2: {
    position: 'absolute',
    height: 100,
    width: 100,
    borderRadius: 50,
    top: 10,
    right: '-5%',
    backgroundColor: whiteThemeColors.greyDark + '06',
  },
  circles3: {
    position: 'absolute',
    height: 150,
    width: 150,
    borderRadius: 80,
    bottom: -70,
    right: '20%',
    backgroundColor: whiteThemeColors.primaryDark + '08',
  },
  flatList: {
    width: '98%',
    marginTop: 5,
  },
  btnTextStyle: {
    textTransform: 'capitalize',
    fontSize: 12,
    fontFamily: CommonStyles.fonts.bold,
  },
  cardContainer: {
    width: '98%',
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
    borderRadius: 20,
    backgroundColor: whiteThemeColors.white + 90,
    paddingVertical: 7,
    marginTop: 8,
  },
  floatingIcon: {
    fontSize: 120,
    position: 'absolute',
    right: -10,
    top: -10,
    color: whiteThemeColors.primary,
    opacity: 0.1,
  },
  headerContainer: {
    paddingBottom: 5,
    marginTop: 5,
    marginLeft: 15,
    borderBottomWidth: 1,
    borderBottomColor: whiteThemeColors.primaryDark,
    alignSelf: 'flex-start',
  },
  innerContainer: {
    alignItems: 'center',
    paddingVertical: 15,
    paddingHorizontal: 15,
    width: '100%',
    borderRadius: 15,
    height: 150,
    overflow: Platform.OS == 'android' ? 'hidden' : 'visible',
  },
  headerText: {
    fontSize: 16,
    color: whiteThemeColors.primaryTextColor,
    fontFamily: CommonStyles.fonts.semiBold,
    textTransform: 'capitalize',

    paddingTop: 20,
  },
  infoContainer: {
    width: '100%',
    flexDirection: 'row',
  },
  text: {
    paddingLeft: 2,
    paddingRight: 10,

    color: whiteThemeColors.lightBlack,
    marginBottom: 10,
    fontFamily: CommonStyles.fonts.semiBold,
    fontSize: 12,
  },
  labelText: {
    fontSize: 12,
    opacity: 0.7,
    color: whiteThemeColors.greyDark,
    fontFamily: CommonStyles.fonts.medium,
  },
  circle2: {
    position: 'absolute',
    height: 100,
    width: 100,
    borderRadius: 50,
    bottom: 10,
    left: '7%',
    backgroundColor: whiteThemeColors.greyDark + '06',
  },
  circle3: {
    position: 'absolute',
    height: 150,
    width: 150,
    borderRadius: 80,
    top: -10,
    left: -30,
    backgroundColor: whiteThemeColors.primaryDark + '08',
  },
  scrollView: {
    flex: 1,
    backgroundColor: whiteThemeColors.background,
  },
  summaryContainer: {
    backgroundColor: whiteThemeColors.background,
    borderTopRightRadius: 20,
    borderTopLeftRadius: 20,
    paddingHorizontal: 10,
    alignSelf: 'center',
    height: '100%',
    width: '100%',
  },
  summary: {
    width: '95%',
    alignSelf: 'center',
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderRadius: 10,
    backgroundColor: whiteThemeColors.greyDark + '08',
    marginVertical: 10,
  },
  circleBtn: {
    position: 'absolute',
    right: 25,
    zIndex: 1,
    backgroundColor: whiteThemeColors.primary + 30,
    borderRadius: 12,
    width: 35,
    height: 35,
    justifyContent: 'center',
    alignItems: 'center',
    top: 20,
  },
  timingCard: {
    flexDirection: 'row',
    width: '100%',
    paddingBottom: 20,
    alignItems: 'flex-end',
  },
  txtContainer: {
    flexDirection: 'row',
    paddingTop: 5,
    width: '47%',
  },
  timeTakenContainer: {
    width: '50%',
    flexDirection: 'row',
    paddingTop: 5,
    paddingLeft: 10,
  },
});
