import { StyleSheet } from 'react-native';
import CommonStyles from 'screens/CommonStyles';
import { whiteThemeColors } from 'utilities';

export const styles = StyleSheet.create({
  cardContainer: {
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    minHeight: 150,
    marginTop: -10,
    backgroundColor: whiteThemeColors.background,
  },
  innerContainer: {
    paddingHorizontal: 15,
    paddingVertical: 10,
    width: '95%',
    height: 130,
    borderRadius: 15,
    overflow: 'hidden',
    backgroundColor: whiteThemeColors.white + 90,
  },
  textTimeContainer: {
    zIndex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    height: '100%',
    width: '100%',
  },
  timeContainer: {
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    marginLeft: 23,
  },
  timeView: {
    height: '90%',
    width: '100%',
    borderRadius: 15,
    backgroundColor: whiteThemeColors.white + 90,
    flexDirection: 'row',
  },
  titleContainer: { marginRight: '10%' },
  noDataContainer: {
    height: '100%',
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  noDataTxt: {
    color: whiteThemeColors.primary,
    fontFamily: CommonStyles.fonts.semiBold,
  },
  textContainer: {
    justifyContent: 'space-between',
    paddingVertical: 5,
    width: '100%',
    marginLeft: -100,
    paddingLeft: 100,
  },
  eventTxt: {
    fontSize: 11,
    color: whiteThemeColors.greyDark,
    opacity: 0.8,
    fontFamily: CommonStyles.fonts.semiBold,
  },
  eventName: {
    fontSize: 16,
    color: whiteThemeColors.black,
    fontFamily: CommonStyles.fonts.semiBold,
  },
  subTxtContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  amountTxt: {
    fontSize: 11,
    color: whiteThemeColors.greyDark,
    opacity: 0.8,
    fontFamily: CommonStyles.fonts.semiBold,
  },
  amount: {
    fontSize: 18,
    color: whiteThemeColors.black,
    fontFamily: CommonStyles.fonts.semiBold,
  },
  couponTxt: {
    fontSize: 11,
    color: whiteThemeColors.greyDark,
    opacity: 0.8,
    fontFamily: CommonStyles.fonts.semiBold,
  },
  couponExistTxt: {
    fontSize: 18,
    color: whiteThemeColors.black,
    fontFamily: CommonStyles.fonts.semiBold,
  },
  dateTimeContainer: {
    flexGrow: 1,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
  },
  dateTimeTxt: {
    fontSize: 11,
    textAlign: 'center',
    padding: 5,
    borderRadius: 10,
    backgroundColor: whiteThemeColors.primary + '05',
    color: whiteThemeColors.white,
    fontFamily: CommonStyles.fonts.semiBold,
  },
  watermarkCircle1: {
    position: 'absolute',
    bottom: -30,
    left: -20,
    height: 100,
    width: 100,
    borderRadius: 50,
    opacity: 0.08,
    backgroundColor: whiteThemeColors.white + 90,
  },
  watermarkCircle2: {
    position: 'absolute',
    top: -50,
    left: '35%',
    height: 125,
    width: 125,
    borderRadius: 65,
    opacity: 0.04,
    backgroundColor: whiteThemeColors.white + 90,
  },
});
