import { Platform, StyleSheet } from 'react-native';
import CommonStyles from 'screens/CommonStyles';
import { whiteThemeColors } from 'utilities';

export const styles = StyleSheet.create({
  cardContainer: {
    width: '100%',
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
    borderRadius: 10,
    backgroundColor: whiteThemeColors.background,
    paddingVertical: 15,
    marginTop: 8,
  },
  innerContainer: {
    alignItems: 'center',
    marginTop: 10,
    paddingVertical: 15,
    paddingHorizontal: 15,
    width: '90%',
    borderRadius: 10,
    overflow: Platform.OS == 'android' ? 'hidden' : 'visible',
    backgroundColor: whiteThemeColors.white,
  },
  headerText: {
    fontSize: 21,
    color: whiteThemeColors.primaryTextColor,
    textTransform: 'capitalize',
    fontFamily: CommonStyles.fonts.semiBold,
    paddingVertical: 20,
  },
  showContacts: {
    backgroundColor: whiteThemeColors.primary,
    height: 20,
    justifyContent: 'center',
    width: 20,
    borderRadius: 7,
    alignSelf: 'flex-end',
  },
  editInfo: {
    borderColor: whiteThemeColors.primary,
    backgroundColor: 'white',
    borderRadius: 9,
    borderWidth: 1,
    height: 18,
    width: 18,
    marginHorizontal: 3,
    marginBottom: 3,
    justifyContent: 'center',
    alignSelf: 'flex-end',
  },
  showContactsContainer: {
    flexDirection: 'row',
    alignSelf: 'flex-end',
    alignItems: 'center',
    marginTop: 15,
  },
  detailscon: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    borderBottomWidth: 1,
    borderBottomColor: whiteThemeColors.greyLite,
    paddingVertical: 15,
  },
  keyText: {
    fontSize: 12,
    fontFamily: CommonStyles.fonts.medium,
  },
  valueText: {
    fontSize: 12,
    color: whiteThemeColors.greyDark,
    fontFamily: CommonStyles.fonts.regular,
  },
  showContactstext: {
    color: whiteThemeColors.black,
    marginRight: 5,
    fontSize: 12,
    fontFamily: CommonStyles.fonts.regular,
  },
  updateInfoText: {
    color: whiteThemeColors.white,
    marginRight: 5,
    fontSize: 12,
  },
  imageContainer: {
    width: 90,
    height: 90,
    borderRadius: 45,
    backgroundColor: whiteThemeColors.background,
    justifyContent: 'center',
    alignItems: 'center',
  },
  inputStyle: {
    flexDirection: 'row',
    width: '100%',
    borderBottomWidth: 1,
    borderBottomColor: whiteThemeColors.greyLite,
    padding: 8,
  },
  updateInfoBtn: {
    borderWidth: 1,
    borderColor: whiteThemeColors.primaryDark + 80,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    marginTop: 6,
    borderRadius: 10,
    paddingVertical: 7,
    justifyContent: 'center',
    backgroundColor: whiteThemeColors.primary + 20,
    width: 200,
    alignSelf: 'center',
  },
  showBtn: {
    borderWidth: 1,
    borderColor: whiteThemeColors.primaryDark + 80,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    marginTop: 6,
    borderRadius: 10,
    paddingVertical: 7,
    justifyContent: 'center',
    backgroundColor: whiteThemeColors.primary + 20,
    width: 200,
    alignSelf: 'center',
  },
  showBtnTxt: {
    color: whiteThemeColors.primaryDark,
    marginLeft: 10,
    fontSize: 12,
    fontFamily: CommonStyles.fonts.semiBold,
  },
  updateInfoTxt: {
    color: whiteThemeColors.primaryDark,
    marginLeft: 10,
    fontSize: 12,
    fontFamily: CommonStyles.fonts.semiBold,
  },
});
