import { Platform, StyleSheet } from 'react-native';
import CommonStyles from '../../../../../CommonStyles';
import { whiteThemeColors } from '../../../../../../Utilities';

export const styles = StyleSheet.create({
  cardContainer: {
    width: '95%',
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
    borderRadius: 20,
    backgroundColor: whiteThemeColors.white + 90,
    paddingVertical: 3,
  },
  innerContainer: {
    alignItems: 'center',
    paddingVertical: 15,
    paddingHorizontal: 15,
    width: '100%',
    borderRadius: 10,
    overflow: Platform.OS == 'android' ? 'hidden' : 'visible',
  },

  summaryStdNameContainer: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    marginBottom: 10,
  },
  summaryStdNameLabelTxt: {
    fontSize: 12,
    marginTop: 5,
  },
  summaryStdNameValueTxt: {
    marginLeft: 15,
    // fontSize: 16,
    marginBottom: 0,
    paddingLeft: 2,
    paddingRight: 10,
    fontSize: 12,
    color: whiteThemeColors.primaryTextColor,
    fontFamily: CommonStyles.fonts.semiBold,
  },
  summaryToggleCardFiguresContianer: {
    width: '100%',
    alignSelf: 'center',
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderRadius: 10,
    backgroundColor: whiteThemeColors.background,
  },
  summaryCardSingleCellContainer: { width: '50%', flexDirection: 'row' },
  summaryCardTotalPointsContainer: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'flex-end',
    marginBottom: 10,
  },
  CardToggleIconContainer: {
    position: 'absolute',
    right: 25,
    zIndex: 1,
    backgroundColor: whiteThemeColors.primary + 30,
    borderRadius: 12,
    width: 35,
    height: 35,
    justifyContent: 'center',
    alignItems: 'center',
    top: 25,
  },
  text: {
    paddingLeft: 2,
    paddingRight: 10,
    fontSize: 12,
    color: whiteThemeColors.greyDark,
    marginBottom: 10,
  },
  circle1: {
    position: 'absolute',
    height: 170,
    width: 170,
    borderRadius: 90,
    bottom: -30,
    right: -30,

    backgroundColor: whiteThemeColors.primary + '07',
  },
  circle2: {
    position: 'absolute',
    height: 100,
    width: 100,
    borderRadius: 50,
    bottom: 10,
    left: '7%',
    backgroundColor: whiteThemeColors.greyDark + '06',
  },
  circle3: {
    position: 'absolute',
    height: 150,
    width: 150,
    borderRadius: 80,
    top: -10,
    left: -30,
    backgroundColor: whiteThemeColors.primaryDark + '08',
  },
  floatingIcon: {
    fontSize: 120,
    position: 'absolute',
    right: -10,
    top: -10,
    color: whiteThemeColors.primaryDark,
    opacity: 0.1,
  },
  labelText: {
    fontSize: 10,
    opacity: 0.7,
    color: whiteThemeColors.greyDark,
    fontFamily: CommonStyles.fonts.medium,
  },
  headerText: {
    fontSize: 16,
    color: whiteThemeColors.primaryTextColor,
    fontFamily: CommonStyles.fonts.semiBold,
    textTransform: 'capitalize',
    marginTop: 10,
  },
  infoRow: {
    flexDirection: 'row',
  },
  totalPointsTxt: {
    marginBottom: 0,
    marginTop: 10,
    fontSize: 16,
    fontFamily: CommonStyles.fonts.bold,
  },
});
