import { Platform, StyleSheet } from 'react-native';
import { isTablet } from 'react-native-device-info';
import CommonStyles from '../../../CommonStyles';
import { getHeight, whiteThemeColors } from '../../../../Utilities';
export const styles = StyleSheet.create({
  topView: {
    width: '95%',
    height: 80,
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: whiteThemeColors.primary + 30,
    borderRadius: 25,
    marginTop: -10,
  },
  topViewButton: {
    width: 50,
    height: 50,
    // marginBottom: 8,
    borderRadius: 15,
    backgroundColor: whiteThemeColors.primary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  border: {
    width: 60,
    height: 60,
    borderRadius: 20,
    backgroundColor: whiteThemeColors.white + 90,
    justifyContent: 'center',
    alignItems: 'center',
  },
  body: {
    flex: 1,
    backgroundColor: whiteThemeColors.background,
    marginTop: 10,
  },
  listView: {
    width: '100%',
    backgroundColor: whiteThemeColors.contentBg,
    borderRadius: 2,
    marginVertical: 4,
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
  },
  flatList: {
    width: '95%',
  },
  classImageView: {
    width: '95%',
    height: getHeight(30),
    margin: 0,
    padding: 0,
    alignSelf: 'center',
    borderRadius: 15,
  },
  classImage: {
    width: '100%',
    height: isTablet() ? getHeight(30) : getHeight(28),
    resizeMode: 'cover',
    borderTopEndRadius: 20,
    borderTopStartRadius: 20,
  },
  dropDownList: {
    width: '50%',
    height: 80,
    borderRadius: 15,
    paddingTop: 5,
    top: 20,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: whiteThemeColors.background,
  },
  dropDownItemTxt: {
    color: whiteThemeColors.black,
    fontSize: 12,

    fontFamily: CommonStyles.fonts.regular,
    backgroundColor: whiteThemeColors.background,
  },
  noDataTxt: {
    marginTop: 170,
    alignSelf: 'center',
    fontSize: 18,
    fontWeight: '500',
    color: whiteThemeColors.primaryTextColor,
    flex: 1,
    fontFamily: CommonStyles.fonts.regular,
  },
  loadingFailedTxt: {
    paddingHorizontal: 15,
    paddingVertical: 10,
    backgroundColor: whiteThemeColors.red,
    color: 'white',
  },
  stepsBtn: {
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 20,
    backgroundColor: whiteThemeColors.white + 90,

    borderRadius: 15,
  },
  touleableRowContainer: {
    flexDirection: 'row',
    width: '100%',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 10,
  },
  iconContainer: {
    marginRight: 5,
  },
  imgView: {
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 20,
  },
  safeAView: {
    width: '100%',
    alignItems: 'center',
    backgroundColor: whiteThemeColors.background,
  },
  svgContainer: {
    backgroundColor: whiteThemeColors.primary + 30,
    width: 30,
    height: 30,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  arrowIcon: {
    backgroundColor: whiteThemeColors.primary,
    height: 30,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    width: 30,
  },
});
