import { StyleSheet } from 'react-native';
import { whiteThemeColors } from 'utilities';
import CommonStyles from '../CommonStyles';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingHorizontal: 10,
    alignItems: 'center',
  },
  profileHeaderContainer: {
    width: '90%',
    backgroundColor: whiteThemeColors.white + 90,
    height: '20%',
    marginTop: 60,
    borderRadius: 15,
    paddingLeft: 100,
  },
  userFullNameTxt: {
    marginTop: 15,
    fontFamily: CommonStyles.fonts.semiBold,
    fontSize: 18,
    textTransform: 'capitalize',
    color: whiteThemeColors.primary,
  },
  userRoleTxt: {
    color: whiteThemeColors.greyDark,
    fontFamily: CommonStyles.fonts.regular,
    textTransform: 'capitalize',
    fontSize: 13,
  },
  changePasswordBtn: {
    width: 155,
    height: 35,
    borderRadius: 10,
    backgroundColor: whiteThemeColors.primary,
    alignSelf: 'flex-end',
    marginTop: 35,
    marginRight: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  changePasswordTxt: {
    fontSize: 13,
    color: whiteThemeColors.white,
    fontFamily: CommonStyles.fonts.semiBold,
  },
  personalInfoContainer: {
    width: '90%',
    marginTop: 60,
    paddingHorizontal: 20,
    backgroundColor: whiteThemeColors.white + 90,
    borderRadius: 15,
    paddingTop: 20,
  },
  personalInfoTxt: {
    fontSize: 18,
    fontFamily: CommonStyles.fonts.semiBold,
    textTransform: 'capitalize',
    color: whiteThemeColors.primary,
    textAlign: 'center',
    marginBotto: 20,
  },
  profilePicContainer: {
    width: 105,
    height: 105,
    backgroundColor: 'white',
    position: 'absolute',
    top: -25,
    left: -12,
    zIndex: 10,
    borderRadius: 25,
    borderWidth: 4,
    borderColor: whiteThemeColors.primary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  profilePicIconContainer: {
    height: 30,
    width: 30,
    borderRadius: 8,
    backgroundColor: whiteThemeColors.white,
    justifyContent: 'center',
    alignItems: 'center',
  },
  profilePic: {
    width: 100,
    height: 100,
    borderRadius: 25,
    backgroundColor: whiteThemeColors.white + 90,
  },
  profilePicBtn: {
    borderRadius: 10,
    position: 'absolute',
    bottom: -10,
    right: -5,
    zIndex: 100,
  },
  uploadPicDropDown: {
    backgroundColor: whiteThemeColors.background,
    shadowColor: whiteThemeColors.black,
    borderRadius: 15,
    zIndex: 10,
    width: 170,
    height: 80,
    top: 145,
    left: 80,
    position: 'absolute',
    padding: 5,
  },
  uploadPicSingleOptionBtn: {
    flex: 1,
    justifyContent: 'space-between',
    alignItems: 'center',
    flexDirection: 'row',

    borderBottomColor: whiteThemeColors.greyDark,
    marginHorizontal: 10,
  },
  uploadPicSingleOptionTxt: {
    textAlign: 'left',
    fontFamily: CommonStyles.fonts.regular,
    color: whiteThemeColors.black,
  },
  userInfoRowContainer: {
    width: '100%',
    paddingHorizontal: 10,
    paddingVertical: 20,
    flexDirection: 'row',
    alignItems: 'center',
    overflow: 'hidden',
    borderBottomWidth: 0.2,
    borderBottomColor: whiteThemeColors.greyDark + 50,
  },
  userInfoTitle: {
    marginLeft: 10,
    fontFamily: CommonStyles.fonts.medium,
  },
  userInfoValue: {
    width: '70%',
    marginLeft: 10,
    fontFamily: CommonStyles.fonts.regular,
    color: whiteThemeColors.greyDark,
  },
  shadow: {
    shadowColor: whiteThemeColors.greyDark,
    shadowOffset: {
      width: 0,
      height: 5,
    },
    shadowOpacity: 0.36,
    shadowRadius: 6.68,
    elevation: 11,
  },
  profilePicShadow: {
    shadowColor: whiteThemeColors.primary,
    shadowOffset: {
      width: 0,
      height: 5,
    },
    shadowOpacity: 0.36,
    shadowRadius: 6.68,
    elevation: 11,
  },
  title: { fontSize: 24, fontWeight: 'bold', marginBottom: 16 },
  card: {
    borderWidth: 1,
    borderColor: '#ccc',
    padding: 12,
    marginBottom: 12,
    borderRadius: 8,
  },
});
