import { Dimensions, Platform, StyleSheet } from 'react-native';
import CommonStyles from 'screens/CommonStyles';
import { whiteThemeColors } from 'utilities';
const deviceHeight = Dimensions.get('window').height;
const pinBtn = 65;
const styles = StyleSheet.create({
  topContainer: {
    flex: 1,
    backgroundColor: whiteThemeColors.black,
    justifyContent: 'center',
    alignContent: 'center',
  },
  cameraContainer: {
    width: 275,
    height: 275,
    borderWidth: 1,
    alignSelf: 'center',
    borderRadius: 10,
    borderColor: whiteThemeColors.white,
    borderStyle: 'dashed',
    overflow: 'hidden',
  },
  cameraStyle: {
    width: '99%',
    alignSelf: 'center',
  },
  markerStyle: {
    color: whiteThemeColors.primary,
    borderRadius: 10,
    borderColor: whiteThemeColors.white,
    borderStyle: 'dashed',
  },
  objText: {
    fontSize: 22,
    fontFamily: CommonStyles.fonts.medium,
    color: whiteThemeColors.white,
  },
  userInfoCon: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 10,
  },
  btnTxt: {
    color: whiteThemeColors.white,
    fontSize: 14,
    marginLeft: 10,
    fontFamily: CommonStyles.fonts.bold,
  },
  btn: {
    width: '70%',
    height: 45,
    // backgroundColor: whiteThemeColors.primary + 90,
    backgroundColor: 'red',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    shadowColor: whiteThemeColors.greyDark,
  },
  btnCon: {
    width: '60%',
    height: 40,
    borderRadius: 8,
    borderColor: 'red',
    justifyContent: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: whiteThemeColors.primary + 90,
  },
  defaultContainer: {
    width: '100%',
    height: '60%',
    justifyContent: 'space-around',
    alignItems: 'center',
  },
  footerNoteTxt: {
    fontSize: 12,
    textAlign: 'center',
    color: whiteThemeColors.greyDark,
    fontFamily: CommonStyles.fonts.regular,
    padding: 20,
  },
  qrDetailsHeaderContainer: {
    width: '100%',
    height: '20%',
    justifyContent: 'space-around',
    alignItems: 'center',
  },
  qrDetailsUpperContainer: {
    width: '100%',
    height: '60%',
    alignItems: 'center',
    backgroundColor: whiteThemeColors.white,
    borderRadius: 20,
    padding: 10,
    shadowColor: whiteThemeColors.greyDark,
  },
  qrDetailsContainer: {
    width: '100%',
    height: '80%',
    justifyContent: 'space-evenly',
    alignItems: 'center',
    marginBottom: 10,
  },
  valueContainer: {
    width: '80%',
    height: '100%',
    alignItems: 'center',
    flexDirection: 'row',
  },
  valueTxt: {
    fontSize: 13,
    marginLeft: 10,
  },
  labelContainer: {
    width: '20%',
    height: '100%',
    alignItems: 'center',
    flexDirection: 'row',
  },
  labelTxt: {
    fontSize: 10,
    color: whiteThemeColors.greyDark,
    marginLeft: 3,
  },
  rowContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
    width: '98%',
  },
  userRoleTxt: {
    fontSize: 10,
    color: whiteThemeColors.greyDark,
    fontFamily: CommonStyles.fonts.regular,
  },
  userNameTxt: {
    fontSize: 20,
    color: whiteThemeColors.primary,
    marginTop: 10,
    fontFamily: CommonStyles.fonts.semiBold,
  },
  avatarContainer: {
    width: '100%',
    height: 90,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 2,
  },
  userInfoContainer: {
    width: '100%',
    height: '20%',
    alignItems: 'center',
  },
  cardShadow: {},
  footerNoteContainer: {
    width: '100%',
    height: '20%',
    paddingHorizontal: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  checkInOutContainer: {
    width: '100%',
    height: '80%',
    padding: 10,
    borderRadius: 5,
    backgroundColor: whiteThemeColors.primary + 10,
  },
  todayDateTxt: {
    fontSize: 16,
    color: whiteThemeColors.greyDark,
    fontFamily: CommonStyles.fonts.regular,
  },
  pinContainer: {
    flex: 1,
    width: '100%',
    height: '100%',
    marginTop: 40,
  },
  logoContainer: {
    width: '100%',
    flex: 6,
    justifyContent: 'center',
  },
  pinInputContainer: {
    width: '100%',
    height: 30,
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  invalidPinContainer: {
    flex: 1,
    alignSelf: 'center',
    justifyContent: 'center',
  },
  switchContainer: {
    top: Platform.OS == 'ios' ? 38 : 10,
    position: 'absolute',
    zIndex: 999,
    right: 25,
  },
  invalidPinTxt: {
    color: whiteThemeColors.white,
    fontSize: 13,
    marginTop: 5,
    fontFamily: CommonStyles.fonts.regular,
  },
  pinIcon: {
    tintColor: whiteThemeColors.primary,
    marginBottom: 5,
    marginLeft: 20,
    height: 38,
    width: 43,
  },
  orientedPinIcon: {
    tintColor: whiteThemeColors.white,
    position: 'absolute',
    top: -20,
    right: 15,
    height: 38,
    width: 43,
  },
  close: {
    top: Platform.OS == 'ios' ? 38 : 10,
    position: 'absolute',
    zIndex: 999,
    left: 25,
  },
  pinInputTxt: {
    fontSize: 15,
    fontFamily: CommonStyles.fonts.semiBold,
    color: whiteThemeColors.white,
  },
  btnContainer: {
    width: '100%',
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  container: {},
  btnRow: {
    flexDirection: 'row',
    alignSelf: 'stretch',
    alignItems: 'center',
    justifyContent: 'space-around',
  },
  keyBtn: {
    height: pinBtn,
    width: pinBtn,
    margin: 10,
    borderColor: whiteThemeColors.white,
    backgroundColor: whiteThemeColors.white + 30,
    // borderWidth: 1,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  smFont: {
    fontSize: 16,
    fontFamily: CommonStyles.fonts.semiBold,
    padding: 15,
    marginLeft: 10,
    marginRight: 10,
  },
  clearAll: {
    color: whiteThemeColors.white,
    fontFamily: CommonStyles.fonts.semiBold,
    marginRight: 10,
    marginLeft: 10,
    fontSize: 16,
    padding: 15,
    width: 80,
  },
  backButton: {
    color: whiteThemeColors.white,
    fontFamily: CommonStyles.fonts.semiBold,
    marginRight: 10,
    marginLeft: 10,
    fontSize: 16,
    padding: 15,
  },
  txwhite: {
    color: whiteThemeColors.white,
  },
  fullHeight: {
    height: deviceHeight,
  },
  backbtn: {
    height: 45,
    width: 45,
    borderRadius: 45 / 2,
    justifyContent: 'center',
    alignItems: 'center',
    margin: Platform.OS === 'ios' ? 10 : 10,
    marginTop: Platform.OS === 'ios' ? 35 : 10,
  },
  BackBtnMargin: {
    position: 'relative',
    fontSize: 35,
    top: Platform.OS === 'ios' ? 35 : 0,
  },
  QrScanner: {
    position: 'relative',
    fontSize: 28,
    top: Platform.OS === 'ios' ? 35 : 0,
  },
});
export default styles;
